<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>dbc34888-de60-4a8f-8661-956f269e45fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.product-hero-images__image-col > div.slider > div.slider-control-centerright > button[type=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[85]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@aria-label = 'next' and @type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b62b6868-e4df-4ae3-9ae6-b6047782a712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>9a8b8313-55ca-40d3-9b36-491371b46b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00743def-d2d6-4cca-8c9a-7fef29e7f5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>cd0ea0fa-f960-4c2d-bd98-30508356b283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page--sticky-nav mouse-click ReactModal__Body--open&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open gallery-modal modal__overlay&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open gallery-modal__content&quot;]/div[@class=&quot;product-hero-images&quot;]/div[@class=&quot;row product-hero-images__image-row&quot;]/div[@class=&quot;product-hero-images__image-col&quot;]/div[@class=&quot;slider&quot;]/div[@class=&quot;slider-control-centerright&quot;]/button[1]</value>
      <webElementGuid>8d9c6e8d-2ea1-48ed-9afd-f5c75d928fcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[85]</value>
      <webElementGuid>b4a96a71-da8c-4526-8eb8-5316c032195a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[3]/following::button[1]</value>
      <webElementGuid>2b17d5bc-1f29-4e8f-8324-d9f528bfc70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slide 6 of 24'])[1]/following::button[4]</value>
      <webElementGuid>a6a7ad60-78c4-4b7b-aecc-f17d3c8c0d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cookie policy.'])[1]/preceding::button[50]</value>
      <webElementGuid>2860742c-682e-43d4-8c3a-76c0d0295503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANAGE PREFERENCES'])[1]/preceding::button[50]</value>
      <webElementGuid>671cfb02-4877-4831-96e5-2b7fa86d121c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/div/div/div[4]/button</value>
      <webElementGuid>9dfc0742-8938-4d60-9f5c-d47a149ec609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>59c7a594-32bd-4c5d-8ec9-8c5513d29988</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
