<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View Shopping Cart</name>
   <tag></tag>
   <elementGuidId>53154c9b-b4fa-433b-8079-3ce1a24537e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[85]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.cart-tooltip__actions-view-cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23023edd-20a2-43a0-be90-3c64349e5dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a04ae194-4044-4f37-ba50-1b40d3d5fe4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>View Shopping Cart</value>
      <webElementGuid>99cc71b4-dcbb-4432-8634-f0fc7e823b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-tooltip__actions-view-cart</value>
      <webElementGuid>94b7ae5d-c2f3-4af9-b8af-94103f1a0ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Shopping Cart</value>
      <webElementGuid>6ad9b2ce-9d53-426e-8efd-8f47645470c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page--sticky-nav ReactModal__Body--open mouse-click&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open cart-modal__overlay&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open cart-modal&quot;]/div[@class=&quot;success-model__wrapper&quot;]/div[@class=&quot;cart-tooltip__actions&quot;]/button[@class=&quot;cart-tooltip__actions-view-cart&quot;]</value>
      <webElementGuid>e58d6c66-c569-4d66-8ee2-51560bbaedfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[85]</value>
      <webElementGuid>54734660-ca2a-47cc-9bfa-0735ed5d6f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping and taxes calculated at checkout.'])[1]/following::button[1]</value>
      <webElementGuid>39e9b854-269b-462b-9407-d3e0b230cf10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$190.99'])[7]/following::button[1]</value>
      <webElementGuid>99a9fe58-017a-47c6-8703-376b62f7855b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout now'])[3]/preceding::button[1]</value>
      <webElementGuid>9b32c954-73d7-439c-981e-6c72be699d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[4]/button</value>
      <webElementGuid>313ee516-e75c-41cc-8e50-eac986aa89df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'View Shopping Cart' or . = 'View Shopping Cart')]</value>
      <webElementGuid>abcecb63-3ea6-4144-aa6f-4d2ee7e6066d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
