<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Powder</name>
   <tag></tag>
   <elementGuidId>70eb4280-9d4b-4c54-a11c-a9d6b5a517c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.product-options__button.product-options__button--active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[46]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'Powder ' or . = 'Powder ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c42ef36c-d3c4-4481-8130-0075d206bc7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d0675f4-64d4-483d-9f86-8dafe81504fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Powder </value>
      <webElementGuid>b39dbf05-e8ef-4528-ad72-8a6528289cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-options__button product-options__button--active</value>
      <webElementGuid>0d4ed31d-dabb-4f84-b7bc-7d6f200baf48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Powder </value>
      <webElementGuid>182b2e88-89d2-41dc-82d5-6dd93b9163b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row product-main&quot;]/div[@class=&quot;content-grid__column product-main__info content-grid__column--size-6&quot;]/div[@class=&quot;product-options__wrapper&quot;]/div[@class=&quot;product-options&quot;]/div[@class=&quot;row product-options__row&quot;]/div[@class=&quot;product-options__content product-options__content--format&quot;]/button[@class=&quot;product-options__button product-options__button--active&quot;]</value>
      <webElementGuid>204ae7c2-45a2-412b-b746-4b2b96806812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[46]</value>
      <webElementGuid>40b874fd-b6df-4434-a100-8db57a89490c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[2]/div[2]/div[3]/div/div/div[2]/button</value>
      <webElementGuid>2cd830a3-d872-40ce-bf89-79202a4c18d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enfamil NeuroPro Infant Formula'])[4]/following::button[1]</value>
      <webElementGuid>723515ef-320f-4628-b059-8035f9bdb892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('What', &quot;'&quot;, 's the difference?')])[1]/following::button[1]</value>
      <webElementGuid>fb19f6ed-12dc-4d6a-bc50-ba1a14a8ef02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liquid'])[1]/preceding::button[1]</value>
      <webElementGuid>36d18dae-3213-4c7e-b009-f985c7a7e630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tub'])[1]/preceding::button[2]</value>
      <webElementGuid>5fc9e2eb-faf9-4650-aa1a-ceee37f82b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Powder']/parent::*</value>
      <webElementGuid>89ce2d79-3129-43ca-ae46-27268f0e4eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div[2]/button</value>
      <webElementGuid>fbf6b1b2-8a8d-44b1-9484-c7f5e8bbc443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Powder ' or . = 'Powder ')]</value>
      <webElementGuid>6fcd9b05-30ae-414c-9984-ea8ca7a8756a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
