<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Triple Prebiotic Immune Blend that incl_5df738</name>
   <tag></tag>
   <elementGuidId>f7964c6e-e58d-4612-a4e4-7fd8569b0927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/article/section/div/div[3]/div/div/div[2]/div[2]/div[4]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Triple Prebiotic Immune Blend that includes 2’-FL HMO†, PDX, and GOS. Each of these prebiotics have been shown to support immune health (based on parent feedback)' or . = 'Triple Prebiotic Immune Blend that includes 2’-FL HMO†, PDX, and GOS. Each of these prebiotics have been shown to support immune health (based on parent feedback)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e4bab1ca-4072-4339-b041-3ac6a390879f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>e73a82f2-c884-4e91-a24d-6f4a777a2ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Triple Prebiotic Immune Blend that includes 2’-FL HMO†, PDX, and GOS. Each of these prebiotics have been shown to support immune health (based on parent feedback)</value>
      <webElementGuid>65130b1e-76fa-4b13-b750-bb7131e8fbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row product-overview-margin animate-row aos-init aos-animate&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;product-overview&quot;]/div[@class=&quot;product-overview__content&quot;]/div[@class=&quot;product-overview__right column--size-5&quot;]/div[@class=&quot;product-overview__highlight-item&quot;]/div[@class=&quot;product-overview__highlight-item__desc&quot;]/div[@class=&quot;h6&quot;]</value>
      <webElementGuid>7f4eef7b-c810-4a03-bdc1-f8176d6e031d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[3]/div/div/div[2]/div[2]/div[4]/div[2]/div</value>
      <webElementGuid>1dd3cc34-90f3-420b-867c-9fe98353b4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Naturally occurring MFGM components*'])[1]/following::div[4]</value>
      <webElementGuid>3f186ead-4d4d-4308-a5a8-3ace0789f360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Omega 3 DHA'])[1]/following::div[8]</value>
      <webElementGuid>b44776b4-2018-46e2-a7df-8635e402b826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Triple Prebiotic Immune Blend that includes 2’-FL HMO']/parent::*</value>
      <webElementGuid>a253d2db-fd98-4055-a041-552e6c667ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div</value>
      <webElementGuid>83f52f1a-288b-4807-b056-03f98f4b8f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Triple Prebiotic Immune Blend that includes 2’-FL HMO†, PDX, and GOS. Each of these prebiotics have been shown to support immune health (based on parent feedback)' or . = 'Triple Prebiotic Immune Blend that includes 2’-FL HMO†, PDX, and GOS. Each of these prebiotics have been shown to support immune health (based on parent feedback)')]</value>
      <webElementGuid>4f531573-53d6-443c-b5d3-9e1a259a1986</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
