<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enfamil NeuroPro Infant FormulaPowder  _3b138e</name>
   <tag></tag>
   <elementGuidId>2878be95-fdb5-499b-9fd7-481cc2d4659f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/header/div[3]/div/div[2]/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.popup-content.cart-tooltip-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c7034e1-f847-4c76-90cc-eb23e4e18d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup-content cart-tooltip-content</value>
      <webElementGuid>ae8d202c-4778-49c1-8a80-096f07818b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enfamil NeuroPro Infant FormulaPowder / Tub / 20.7 oz Tub (Case of 6)$190.99 x 1Subtotal$190.99Shipping and taxes calculated at checkout.View Shopping CartCheckout now</value>
      <webElementGuid>8d5498c2-7c32-4259-9ad0-22cc006e8336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/header[@class=&quot;main-header main-header--fixed-mobileOnly&quot;]/div[@class=&quot;main-header__bottom&quot;]/div[@class=&quot;wrapper wrapper--main-header__bottom-items&quot;]/div[@class=&quot;main_header__contents&quot;]/div[@class=&quot;popup-content cart-tooltip-content&quot;]</value>
      <webElementGuid>0e170bae-16e8-49f2-bde4-98457eba86ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/header/div[3]/div/div[2]/div[5]</value>
      <webElementGuid>6f1c63f8-5586-47f6-83a4-0c46dba65066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open search box'])[1]/following::div[4]</value>
      <webElementGuid>0f4b60d8-bc02-4add-8d16-3f5d88fdeba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show contact page'])[1]/following::div[5]</value>
      <webElementGuid>c7c37cb0-a2e6-423d-ba9e-e4c4d21fb220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]</value>
      <webElementGuid>f61996b4-5ede-4596-9838-b0853708c91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Enfamil NeuroPro Infant FormulaPowder / Tub / 20.7 oz Tub (Case of 6)$190.99 x 1Subtotal$190.99Shipping and taxes calculated at checkout.View Shopping CartCheckout now' or . = 'Enfamil NeuroPro Infant FormulaPowder / Tub / 20.7 oz Tub (Case of 6)$190.99 x 1Subtotal$190.99Shipping and taxes calculated at checkout.View Shopping CartCheckout now')]</value>
      <webElementGuid>1140a3b0-0703-4b6f-bcb0-91d8ff512304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
