<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Customers also viewed</name>
   <tag></tag>
   <elementGuidId>86662365-af9a-4273-bf3a-1bed1acdd6f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/article/section/div/div[8]/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.title__heading</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//h2[(text() = 'Customers also viewed' or . = 'Customers also viewed')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c835f80b-620e-456a-b9e3-aa62a267745a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title__heading</value>
      <webElementGuid>fc5ce8cd-6a3a-4900-abda-87f3abf77de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customers also viewed</value>
      <webElementGuid>85e2034c-62d4-4b30-a4fb-f09ceebdc6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row margin-top-tiny content-grid--full-width personalization-featured-products-pdp shop-category animate-row aos-init aos-animate&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;title text-center h3&quot;]/h2[@class=&quot;title__heading&quot;]</value>
      <webElementGuid>6b984feb-a39c-40d9-afa9-e1eabd14b669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[8]/div/div/h2</value>
      <webElementGuid>d77ced55-1f0d-4b0f-b781-034a83e1c736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::h2[1]</value>
      <webElementGuid>d5dff7e4-a6ee-4bea-af59-df1962ec521e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/following::h2[1]</value>
      <webElementGuid>0e8e9208-6846-434e-bb4e-d34a39f98b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slide 1 of 3'])[1]/preceding::h2[1]</value>
      <webElementGuid>c7899dd7-4893-4381-8f2b-d99d889c4528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For fussiness, crying, gas and spit-up'])[1]/preceding::h2[1]</value>
      <webElementGuid>837dc73e-ef96-452c-8694-127d40973cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customers also viewed']/parent::*</value>
      <webElementGuid>6fe258db-b7d4-435a-90bc-9fc5738787d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[8]/div/div/h2</value>
      <webElementGuid>ea2996cc-eb50-4a0f-b066-a5c6922b0a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Customers also viewed' or . = 'Customers also viewed')]</value>
      <webElementGuid>553168e6-810d-4dd5-aaff-1dd517556e91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
