<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Enfamil NeuroPro</name>
   <tag></tag>
   <elementGuidId>d522bb8b-5deb-4166-9933-787a2ccdad3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/article/section/div/div[3]/div/div/div[2]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.h3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Enfamil NeuroPro' or . = 'Enfamil NeuroPro')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c4622775-7789-473d-846c-0c142e8277b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>c3f14ab5-1cbf-4cc7-b028-66fb4d2d30b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enfamil NeuroPro</value>
      <webElementGuid>47d1478c-7318-4c8e-8744-a602a74fa641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row product-overview-margin animate-row aos-init aos-animate&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;product-overview&quot;]/div[@class=&quot;product-overview__content&quot;]/div[@class=&quot;product-overview__left column--size-7&quot;]/h2[@class=&quot;h3&quot;]</value>
      <webElementGuid>e7658f11-d219-425a-a2c7-2a8008d2200c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[3]/div/div/div[2]/div/h2</value>
      <webElementGuid>953d29ac-21c6-475f-bb3d-d8d3af2c8ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/following::h2[1]</value>
      <webElementGuid>9952dbba-148f-4f90-9fbd-17dbf15ff0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need it faster?'])[1]/following::h2[1]</value>
      <webElementGuid>7a9896cf-aaa5-470b-8980-c128b51063e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TM'])[1]/preceding::h2[1]</value>
      <webElementGuid>8343ffc0-a7c4-4713-b4a0-0ef3469d95ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='†'])[1]/preceding::h2[1]</value>
      <webElementGuid>2c85a4d0-5d94-436b-930e-775cef6ba06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enfamil NeuroPro']/parent::*</value>
      <webElementGuid>508704ab-4278-470e-901d-4822a92680cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2</value>
      <webElementGuid>de706b16-a323-47f0-932a-d31be379f9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Enfamil NeuroPro' or . = 'Enfamil NeuroPro')]</value>
      <webElementGuid>dca2048a-2d75-497c-b308-9fed0fe8fc02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
