<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Our Enfamil NeuroPro Baby Formula feature_c61ff3</name>
   <tag></tag>
   <elementGuidId>3c1463c5-8d4c-427a-9b58-b1b89f2a9e5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/article/section/div/div[3]/div/div/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.p3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Our Enfamil NeuroPro Baby Formula features a range of different size options. You can conveniently purchase this Baby Formula in either Powder and Liquid form. The Powder product is available in 20.7 oz Tubs, 31.4 oz Refill Boxes and 17.6g Single Serve Packet Sticks. The Liquid form comes in 2 fl oz, 6 fl oz, 8 fl oz and 32 fl oz bottles. You can also purchase Enfamil NeuroPro Baby Formula Powder in a bulk order with our convenient Case of 6 Tubs, Case of 4 Refill Boxes and Case of 56 Single Serve Packet Sticks. Liquid formula comes in Case of 24 for 2 fl oz, 6 fl oz or 8 fl oz bottles and Case of 6 32 fl oz bottles.' or . = 'Our Enfamil NeuroPro Baby Formula features a range of different size options. You can conveniently purchase this Baby Formula in either Powder and Liquid form. The Powder product is available in 20.7 oz Tubs, 31.4 oz Refill Boxes and 17.6g Single Serve Packet Sticks. The Liquid form comes in 2 fl oz, 6 fl oz, 8 fl oz and 32 fl oz bottles. You can also purchase Enfamil NeuroPro Baby Formula Powder in a bulk order with our convenient Case of 6 Tubs, Case of 4 Refill Boxes and Case of 56 Single Serve Packet Sticks. Liquid formula comes in Case of 24 for 2 fl oz, 6 fl oz or 8 fl oz bottles and Case of 6 32 fl oz bottles.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4ac7d527-1440-4ce2-9eb6-e38fe156c81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p3</value>
      <webElementGuid>43a8444c-1fa3-4585-ab37-2019996ab5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Our Enfamil NeuroPro Baby Formula features a range of different size options. You can conveniently purchase this Baby Formula in either Powder and Liquid form. The Powder product is available in 20.7 oz Tubs, 31.4 oz Refill Boxes and 17.6g Single Serve Packet Sticks. The Liquid form comes in 2 fl oz, 6 fl oz, 8 fl oz and 32 fl oz bottles. You can also purchase Enfamil NeuroPro Baby Formula Powder in a bulk order with our convenient Case of 6 Tubs, Case of 4 Refill Boxes and Case of 56 Single Serve Packet Sticks. Liquid formula comes in Case of 24 for 2 fl oz, 6 fl oz or 8 fl oz bottles and Case of 6 32 fl oz bottles.</value>
      <webElementGuid>f195a73f-40f1-45b3-ad18-d6b5592bb040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row product-overview-margin animate-row aos-init aos-animate&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;product-overview&quot;]/div[@class=&quot;product-overview__content&quot;]/div[@class=&quot;product-overview__left column--size-7&quot;]/p[@class=&quot;p3&quot;]</value>
      <webElementGuid>1a612ac0-42e2-4570-932d-b434ea627c2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[3]/div/div/div[2]/div/p</value>
      <webElementGuid>fe669d34-b09d-4f1c-80f2-66309edd81ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TM'])[1]/following::p[1]</value>
      <webElementGuid>1d15223c-4732-4c2d-8b22-a9ae938465c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enfamil NeuroPro'])[1]/following::p[1]</value>
      <webElementGuid>ca389f1c-263d-439b-8b9a-5ba27e68b48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='†'])[1]/preceding::p[1]</value>
      <webElementGuid>7e221763-4437-44f0-8523-0f12e51fd2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*From whey protein concentrate composed of fats and proteins'])[1]/preceding::p[2]</value>
      <webElementGuid>3de659a0-d4ee-411d-a8df-7ec217cefc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Our Enfamil NeuroPro Baby Formula features a range of different size options. You can conveniently purchase this Baby Formula in either Powder and Liquid form. The Powder product is available in 20.7 oz Tubs, 31.4 oz Refill Boxes and 17.6g Single Serve Packet Sticks. The Liquid form comes in 2 fl oz, 6 fl oz, 8 fl oz and 32 fl oz bottles. You can also purchase Enfamil NeuroPro Baby Formula Powder in a bulk order with our convenient Case of 6 Tubs, Case of 4 Refill Boxes and Case of 56 Single Serve Packet Sticks. Liquid formula comes in Case of 24 for 2 fl oz, 6 fl oz or 8 fl oz bottles and Case of 6 32 fl oz bottles.']/parent::*</value>
      <webElementGuid>53702443-0f3c-405f-a6af-4b4301f5b4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/p</value>
      <webElementGuid>aca72090-171d-4c1c-a575-870eb5ceca90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Our Enfamil NeuroPro Baby Formula features a range of different size options. You can conveniently purchase this Baby Formula in either Powder and Liquid form. The Powder product is available in 20.7 oz Tubs, 31.4 oz Refill Boxes and 17.6g Single Serve Packet Sticks. The Liquid form comes in 2 fl oz, 6 fl oz, 8 fl oz and 32 fl oz bottles. You can also purchase Enfamil NeuroPro Baby Formula Powder in a bulk order with our convenient Case of 6 Tubs, Case of 4 Refill Boxes and Case of 56 Single Serve Packet Sticks. Liquid formula comes in Case of 24 for 2 fl oz, 6 fl oz or 8 fl oz bottles and Case of 6 32 fl oz bottles.' or . = 'Our Enfamil NeuroPro Baby Formula features a range of different size options. You can conveniently purchase this Baby Formula in either Powder and Liquid form. The Powder product is available in 20.7 oz Tubs, 31.4 oz Refill Boxes and 17.6g Single Serve Packet Sticks. The Liquid form comes in 2 fl oz, 6 fl oz, 8 fl oz and 32 fl oz bottles. You can also purchase Enfamil NeuroPro Baby Formula Powder in a bulk order with our convenient Case of 6 Tubs, Case of 4 Refill Boxes and Case of 56 Single Serve Packet Sticks. Liquid formula comes in Case of 24 for 2 fl oz, 6 fl oz or 8 fl oz bottles and Case of 6 32 fl oz bottles.')]</value>
      <webElementGuid>d1d293c9-c58d-467a-a69b-83dfa6dcfb79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
