<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_190.99</name>
   <tag></tag>
   <elementGuidId>5d377ba0-31cd-422f-aa4b-9c97764c2e96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'price--slashed']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.price--slashed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Enfamil NeuroPro Infant Formula'])[7]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78a793d0-c632-4135-9678-ecac4e919cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price--slashed</value>
      <webElementGuid>2a4d9476-9bbf-4220-9bb7-4653babf3d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$190.99</value>
      <webElementGuid>f5b2c872-7857-47ac-8fad-017f57f6a6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page--sticky-nav mouse-click ReactModal__Body--open&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open modal__overlay formula-calculator modal-slide-info subscribe-save-popup overlay tooltip__overlay&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open modal formula-calculator modal-slide-info subscribe-save-popup overlay tooltip&quot;]/section[@class=&quot;overlay-containter&quot;]/div[@class=&quot;overlay&quot;]/p[@class=&quot;overlay__content&quot;]/p[1]/div[@class=&quot;product__subscribe--price&quot;]/div[@class=&quot;product__subscribe--price-container&quot;]/div[@class=&quot;product__subscribe-price&quot;]/span[@class=&quot;price--slashed&quot;]</value>
      <webElementGuid>4226d224-54d8-423c-8e84-946f018a9a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enfamil NeuroPro Infant Formula'])[7]/following::span[1]</value>
      <webElementGuid>9f3b5fba-3624-4317-9c24-126bfc0c16c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe to Save'])[1]/following::span[1]</value>
      <webElementGuid>df578e59-5d2f-42a5-a34b-82febf4d994c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$143.24'])[3]/preceding::span[1]</value>
      <webElementGuid>eadde2cc-df0d-4ff8-8d84-b8982648fe47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your savings'])[1]/preceding::span[2]</value>
      <webElementGuid>2f922cfc-1b24-4dde-a5cd-15aa0373842d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/div/div[2]/div[2]/span</value>
      <webElementGuid>301cbd9e-f64c-4594-b9d3-9a7b0d1019f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$190.99' or . = '$190.99')]</value>
      <webElementGuid>e04a6891-4aaa-4c13-bc6e-b24714047d62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
