<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_171.89</name>
   <tag></tag>
   <elementGuidId>7bb4f605-1bb1-42fd-b088-7c82481b9241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class = 'price__value price__value--original']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '$171.89' or . = '$171.89')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.price__value.price__value--discounted > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c1605b12-75f9-47b8-ade2-6f20cfaa00f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$171.89</value>
      <webElementGuid>02ff60e3-1c3a-40e8-9c79-533e8cdb2567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row product-main-desktop-title&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;product-options product-cta--wrapper&quot;]/div[@class=&quot;product-options__price&quot;]/div[@class=&quot;add-to-cart&quot;]/div[@class=&quot;subscription&quot;]/div[@class=&quot;product-options__price-container&quot;]/div[@class=&quot;product-options__price-info&quot;]/div[@class=&quot;product-options__price-stock-available&quot;]/div[@class=&quot;price&quot;]/div[@class=&quot;price__value price__value--discounted&quot;]/span[1]</value>
      <webElementGuid>cc252dad-cb5e-4430-b7fc-6d417e55b945</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div/span</value>
      <webElementGuid>86e5782b-115b-4956-a766-16e8f5cbff1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$190.99'])[2]/following::span[1]</value>
      <webElementGuid>5c5a101d-8313-4292-b504-8d0bbcfc199a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$143.24'])[1]/following::span[1]</value>
      <webElementGuid>f6d4774a-9e58-4820-beed-fd207e589a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEst'])[1]/preceding::span[1]</value>
      <webElementGuid>369d2ac3-35ab-48a3-86d0-49b7ff43c290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$171.89']/parent::*</value>
      <webElementGuid>af0ad91e-3e2e-485b-ab22-d9fe4663f65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/span</value>
      <webElementGuid>22478c23-95d5-4d6c-80ae-c61a38d006cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$171.89' or . = '$171.89')]</value>
      <webElementGuid>cbe61b6a-c6fc-4ced-9dfd-1780c156ec68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
