<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select one_single-select__indicator single-select__dropdown-indicator css-1gtu0rj-indicatorContainer</name>
   <tag></tag>
   <elementGuidId>24618007-884d-4676-aa5a-6b98a0ae0f85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;22196_c53e0840-3d96-4439-9a91-577015717d2c&quot;)/div[@class=&quot;single-select__control single-select__control--is-focused single-select__control--menu-is-open css-1pahdxg-control&quot;]/div[@class=&quot;single-select__indicators css-1wy0on6&quot;]/div[@class=&quot;single-select__indicator single-select__dropdown-indicator css-1gtu0rj-indicatorContainer&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.single-select__indicator.single-select__dropdown-indicator.css-1gtu0rj-indicatorContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='single-select__menu-list css-11unzgr']/div[${i}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9dd0050-5eaa-43b0-a7d6-4941e93b008d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>44a9b61b-fa7f-4d92-ae12-50fe4a09688f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>single-select__indicator single-select__dropdown-indicator css-1gtu0rj-indicatorContainer</value>
      <webElementGuid>5fdca3cc-a8cf-42b4-b0d6-f15a8d54a673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22196_c53e0840-3d96-4439-9a91-577015717d2c&quot;)/div[@class=&quot;single-select__control single-select__control--is-focused single-select__control--menu-is-open css-1pahdxg-control&quot;]/div[@class=&quot;single-select__indicators css-1wy0on6&quot;]/div[@class=&quot;single-select__indicator single-select__dropdown-indicator css-1gtu0rj-indicatorContainer&quot;]</value>
      <webElementGuid>39d3fa98-5100-4921-a85a-63d65326b34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder (1)/Page_Enspire Family Beginnings Registration  Enfamil/div_State</value>
      <webElementGuid>869c6b2e-e276-4601-b4ea-ac7412c3c58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ead1fa0c-7980-4402-8663-49c38408032c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='22196_c53e0840-3d96-4439-9a91-577015717d2c']/div/div[2]/div</value>
      <webElementGuid>5693a48e-19f3-4e69-847d-d6714c634044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select one'])[1]/following::div[2]</value>
      <webElementGuid>6fd87278-0bc3-42af-b06a-537a1ec6e015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship to child'])[2]/following::div[6]</value>
      <webElementGuid>cb0b9d82-96a9-4500-8899-21e7e9ee87b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mother'])[1]/preceding::div[1]</value>
      <webElementGuid>15baf524-4159-4d45-a350-1bf3c3879688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Father'])[1]/preceding::div[2]</value>
      <webElementGuid>6bcf364b-fc75-45b6-b1c1-69eb4b12bcbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div</value>
      <webElementGuid>29c5a85d-06cf-4900-ba48-159940a0b4a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
