<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip code</name>
   <tag></tag>
   <elementGuidId>cec0f71f-09a7-4cf1-9c0d-ebb9f21f7eca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22218_699e6d61-72d6-44bf-91fc-5f3a714f1fb8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='22218_699e6d61-72d6-44bf-91fc-5f3a714f1fb8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13b6dc52-dbff-4bd7-99b4-0f2be15e4e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--address-postal</value>
      <webElementGuid>4b007b62-72ba-4063-b18c-942e3dd7d9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22218_699e6d61-72d6-44bf-91fc-5f3a714f1fb8</value>
      <webElementGuid>12401fcc-5f59-488e-8618-b1db01c8a69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>699e6d61-72d6-44bf-91fc-5f3a714f1fb8</value>
      <webElementGuid>d99bbe3b-528a-484a-b740-a311e1459448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip code</value>
      <webElementGuid>3da13130-23fc-407a-b6f6-38ce3d427560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27b2ece5-19f7-451d-920c-9fad9381b562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>31f94d7a-bd11-4d6d-9497-b9ab9da663ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22218_699e6d61-72d6-44bf-91fc-5f3a714f1fb8&quot;)</value>
      <webElementGuid>b19fd909-cdde-42fd-b8b2-6cc0bb8f5acf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='22218_699e6d61-72d6-44bf-91fc-5f3a714f1fb8']</value>
      <webElementGuid>f1f1655b-45b9-4b83-af61-24370144e490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[5]/div/div/section/div/div[2]/div[3]/div/input</value>
      <webElementGuid>a8214418-a193-4668-b233-c0d51929259c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>aab66ad8-608d-41d9-86df-6076e57d552e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '22218_699e6d61-72d6-44bf-91fc-5f3a714f1fb8' and @name = '699e6d61-72d6-44bf-91fc-5f3a714f1fb8' and @placeholder = 'Zip code' and @type = 'text']</value>
      <webElementGuid>e0b7f745-e369-44a8-a7ee-bf5897f7fb40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
