<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_State</name>
   <tag></tag>
   <elementGuidId>6960c820-2286-4a9a-a0da-339a303f7c40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'State' or . = 'State')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.single-select__placeholder.css-1wa3eu0-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'State' or . = 'State*')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4759908-8e02-4b1e-a669-9db20676e893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>single-select__placeholder css-1wa3eu0-placeholder</value>
      <webElementGuid>11ed4d22-a62f-4e19-bacb-ab7d81d52925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>State</value>
      <webElementGuid>d1fd57f7-f8c5-4646-a0da-3b4ddea71035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f9acd18e-7be3-472a-9f63-3affc22b70db&quot;)/div[@class=&quot;single-select__control single-select__control--is-focused css-1pahdxg-control&quot;]/div[@class=&quot;single-select__value-container css-1hwfws3&quot;]/div[@class=&quot;single-select__placeholder css-1wa3eu0-placeholder&quot;]</value>
      <webElementGuid>b000011f-3512-488a-be4a-81e0b1a5b2b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f9acd18e-7be3-472a-9f63-3affc22b70db']/div/div/div</value>
      <webElementGuid>db9b03fb-e49a-46ae-ad6b-4d2c5f7477bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::div[4]</value>
      <webElementGuid>492807d5-b956-4925-b8b4-2a20386ac21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City field is required.'])[1]/following::div[6]</value>
      <webElementGuid>e70a7e85-74c4-47f5-921d-6577ee7735e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip code'])[1]/preceding::div[6]</value>
      <webElementGuid>ccc5141b-4df2-4798-b72b-de40b5d9cca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country Code'])[1]/preceding::div[8]</value>
      <webElementGuid>5c4f19c7-f929-4c16-8dfa-5b50afdbace2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>ab56c728-fc86-49cc-88ef-3df4c2675859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'State' or . = 'State')]</value>
      <webElementGuid>850e7352-d54d-4775-b6b3-287b27c4bdb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
