<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_f79d7000-6316-40fb-a3e6-b1f_b5683d</name>
   <tag></tag>
   <elementGuidId>dcf16170-31ca-4583-879e-8f8d0fa1b823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f79d7000-6316-40fb-a3e6-b1fa3d3d39f3_964</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder = 'Last name']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[(@placeholder = 'Last Name' or @placeholder = 'Last Name*')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9cda090-2bec-46d7-9989-a7c6457c5f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--family-name</value>
      <webElementGuid>dd19d1bb-8484-473c-ae71-93a1746f993e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f79d7000-6316-40fb-a3e6-b1fa3d3d39f3_964</value>
      <webElementGuid>75237b51-935a-433a-96cd-4f730bafa8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f79d7000-6316-40fb-a3e6-b1fa3d3d39f3</value>
      <webElementGuid>2d28c837-ca37-43fe-b90d-18b4de6f81f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>08b62260-66f6-4482-9dc1-743ccdce5920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4fab1d38-2de4-4ff4-99e5-84cc88226b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f79d7000-6316-40fb-a3e6-b1fa3d3d39f3_964&quot;)</value>
      <webElementGuid>ca7e523c-9355-4013-9b0a-f23f1e38f074</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f79d7000-6316-40fb-a3e6-b1fa3d3d39f3_964']</value>
      <webElementGuid>b983ca83-d43b-46db-a0a5-d04446b6c917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[2]/div[2]/div/input</value>
      <webElementGuid>bc0f0d2e-91eb-4198-a95d-347ba3d44b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ebda5c15-783a-43ac-a0d9-2f264dd90c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f79d7000-6316-40fb-a3e6-b1fa3d3d39f3_964' and @name = 'f79d7000-6316-40fb-a3e6-b1fa3d3d39f3' and @placeholder = 'Last name' and @type = 'text']</value>
      <webElementGuid>0d7ce31f-bc94-4350-9956-87d7d8bc865d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
