<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a</name>
   <tag></tag>
   <elementGuidId>41939bac-6ac9-477a-a9da-deb087ac7571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_775</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_775']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder = 'Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_775</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_775&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_775']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[3]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_775' and @name = '9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a' and @placeholder = 'Email' and @type = 'email']</value>
   </webElementXpaths>
</WebElementEntity>
