<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a</name>
   <tag></tag>
   <elementGuidId>41939bac-6ac9-477a-a9da-deb087ac7571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_775</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder = 'Email']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'Email*']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f30f04ec-9cc4-49b5-83a5-19303561b83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--login</value>
      <webElementGuid>1a81dcec-ebf6-4a9b-86a9-6cda52b6f6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_775</value>
      <webElementGuid>70ea0286-f152-47d5-9d50-77f4edc089ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a</value>
      <webElementGuid>37296235-e7f4-4f9d-bafc-715dc3dc5303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>a9f3d232-fd64-4a17-9b8d-8230d4f5cfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>16fe21b9-0d8f-46ed-a137-2e28804d9aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_775&quot;)</value>
      <webElementGuid>e20c2062-048e-48e6-98a3-84cef92d1ce0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_775']</value>
      <webElementGuid>ddafa5a8-b9a1-48a2-9b2b-53b9e6f10603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[3]/div/div/input</value>
      <webElementGuid>3eda3b13-13ba-48fb-ac94-c954ffd364d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>943a15ab-9dd7-410c-be18-c3f0b9a718ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_775' and @name = '9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a' and @placeholder = 'Email' and @type = 'email']</value>
      <webElementGuid>0afbd8e8-c431-4472-992c-d801575b546d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
