<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select oneMotherFatherGrandparentOther</name>
   <tag></tag>
   <elementGuidId>6d37d4a9-0c21-4aa5-a89e-7e6304a3e0c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22196_c53e0840-3d96-4439-9a91-577015717d2c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='22196_c53e0840-3d96-4439-9a91-577015717d2c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a4772da7-4dcf-42cf-b550-be6ef490e8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--select</value>
      <webElementGuid>ed7765b1-21e5-418a-bbea-14ada53ff64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22196_c53e0840-3d96-4439-9a91-577015717d2c</value>
      <webElementGuid>2128ed24-8674-4c7a-84e2-6b49081fe9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>22196_c53e0840-3d96-4439-9a91-577015717d2c</value>
      <webElementGuid>44cfbd74-657c-4e9d-969d-19558c60e34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select one</value>
      <webElementGuid>6b5cb71a-f128-4f4b-a8ba-4bcc263c302b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Relationship to child: Select one</value>
      <webElementGuid>8b068c35-0ff8-4cf5-94f2-cbeec5c51877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c95c43bd-3cf4-415a-ae8e-2a26e554c28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select oneMotherFatherGrandparentOther</value>
      <webElementGuid>e8cf6571-cfee-45bd-b8df-feb6c3db362e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22196_c53e0840-3d96-4439-9a91-577015717d2c&quot;)</value>
      <webElementGuid>80a3fa77-a7c4-4c67-9c67-366dc3a7844d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='22196_c53e0840-3d96-4439-9a91-577015717d2c']</value>
      <webElementGuid>1e077d1a-2bd5-4a19-a32a-678cf91b3c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[11]/div/div/section/div/div/div/div[3]/select</value>
      <webElementGuid>4b70a672-c4b7-4be1-bccd-7305f66d9509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship to child'])[2]/following::select[1]</value>
      <webElementGuid>a3a9db99-a4c0-4ec5-8539-777542255f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why?'])[1]/following::select[1]</value>
      <webElementGuid>b6ad4391-4f4a-4904-a86d-d8a52ae30262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How are you currently feeding your little one?'])[1]/preceding::select[1]</value>
      <webElementGuid>870cf931-f97b-4285-90c3-1b3421634c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(optional)'])[1]/preceding::select[1]</value>
      <webElementGuid>07ec1f0d-a839-436d-92e6-56a77cffced3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>c66e8c8d-5e01-409b-a0eb-068da0139338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '22196_c53e0840-3d96-4439-9a91-577015717d2c' and @name = '22196_c53e0840-3d96-4439-9a91-577015717d2c' and @placeholder = 'Select one' and (text() = 'Select oneMotherFatherGrandparentOther' or . = 'Select oneMotherFatherGrandparentOther')]</value>
      <webElementGuid>0c763107-177d-4792-a786-637d3e631de2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
