<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Compare</name>
   <tag></tag>
   <elementGuidId>1026803f-8517-4b03-ab94-dcb9a84086e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[3]/div/div/a/div[5]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@aria-label = 'Compare - Enfamil Enspire Infant Formula']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>855731f1-7c7a-434e-b201-dd49ef9bf351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-item__compare link</value>
      <webElementGuid>34b19207-c16c-45ea-bae8-2f51519f8275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Compare - Enfamil Enspire Infant Formula</value>
      <webElementGuid>dc98767d-4e52-4f1a-926f-ede113b555cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/product-comparison/?product=enfamil-enspire-infant-formula</value>
      <webElementGuid>99bd3199-42cd-43d8-ba1b-6ea0b0d5a247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compare</value>
      <webElementGuid>172c55db-e809-4fe9-ab4b-6aff05565210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app CoreHomePage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid content-grid--main&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row content-grid--full-width  categories-tab categories-tab--center list-child-pages-cards zindex-2 page-border-radius&quot;]/div[@class=&quot;content-grid__column list-child-pages-image-bottom-right margin-bottom-xxlarge hide-filter-pagination content-grid__column--size-12&quot;]/div[@class=&quot;grid-wrapper slideshow-picker slideshow-picker--tab&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;slideshow-picker__slide slideshow-picker__slide--active&quot;]/section[@class=&quot;content-grid content-grid--main&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row&quot;]/div[@class=&quot;content-grid__column hide-filter-pagination content-grid__column--size-12&quot;]/div[@class=&quot;row product-list product-list--shopify search-results--no-products&quot;]/div[@class=&quot;col product-list__products&quot;]/div[@class=&quot;slider&quot;]/div[@class=&quot;slider-frame&quot;]/ul[@class=&quot;slider-list&quot;]/li[@class=&quot;slider-slide slide-visible&quot;]/div[@class=&quot;col product-item product-item--shopify product-item--visible product-item--family&quot;]/div[@class=&quot;row product-item__content&quot;]/a[@class=&quot;product-item__link product-item__link--with-promotion link&quot;]/div[@class=&quot;product-item__actions&quot;]/a[@class=&quot;product-item__compare link&quot;]</value>
      <webElementGuid>41f809ab-51cc-4c39-8396-2b55bd3696a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[8]/div/div[2]/div/div/div/section/div/div/div/div/div/div/div[2]/ul/li[3]/div/div/a/div[5]/a[2]</value>
      <webElementGuid>32b80daf-ccb7-4908-a017-439b35c45f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[3]/following::a[1]</value>
      <webElementGuid>91c9861e-20cd-427c-a75f-2175015fa474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$31.49'])[1]/following::a[2]</value>
      <webElementGuid>f6f9c566-3649-4108-b643-2eb880dba9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For sensitive tummies.'])[1]/preceding::a[1]</value>
      <webElementGuid>83be2cb2-5c89-4a5f-96e6-1d602cbe6408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/product-comparison/?product=enfamil-enspire-infant-formula')]</value>
      <webElementGuid>45b3dfa5-99cf-456e-b030-2bebbb8a7caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/a/div[5]/a[2]</value>
      <webElementGuid>5f80a7d5-6165-44ac-922a-384936170c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/product-comparison/?product=enfamil-enspire-infant-formula' and (text() = 'Compare' or . = 'Compare')]</value>
      <webElementGuid>8c72bf21-0cab-4226-9db5-15ce0a4d551a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
