<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enfamil Shop</name>
   <tag></tag>
   <elementGuidId>f7ec8624-98d3-4fd4-abba-75b390195fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='guarantees-promo-content__title'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.guarantees-promo-content__title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'guarantees-promo-content__title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8415bab7-8dcd-476d-922f-96d8553d59ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>guarantees-promo-content__title</value>
      <webElementGuid>3b6c9417-5bb8-4a4c-993c-41c926576ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enfamil Shop</value>
      <webElementGuid>2de3120c-454c-4391-8d58-11696f889a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app CoreHomePage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid content-grid--main&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row page-border-radius content-grid--full-width guarantees-promo personalization-home-rtb zindex-2&quot;]/div[@class=&quot;content-grid__column no-padding content-grid__column--size-12&quot;]/div[@class=&quot;carousel&quot;]/div[@class=&quot;carousel-item carousel-item--text-only carousel-item--col&quot;]/div[@class=&quot;carousel-item__content-wrapper carousel-item__content-wrapper--above&quot;]/div[@class=&quot;carousel-item__content&quot;]/div[@class=&quot;rte-wrapper&quot;]/div[@class=&quot;rte&quot;]/div[@class=&quot;rte__text carousel-item__description&quot;]/div[@class=&quot;guarantees-promo-heading&quot;]/div[@class=&quot;guarantees-promo-content__title&quot;]</value>
      <webElementGuid>2903556c-5bce-4a68-9a66-b866aa1eccbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[12]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>5b1d6e2f-8653-40f2-be4b-9f1369476a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load more'])[2]/following::div[12]</value>
      <webElementGuid>a396c333-31fe-493d-90db-ed48e4c40a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We can help you to understand the difference between excessive, unexplained...'])[1]/following::div[15]</value>
      <webElementGuid>f2ee9ea6-63c5-4a88-8ff4-d3794e828224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Prices you', &quot;'&quot;, 'll love. Products you trust. Convenience you need.')])[1]/preceding::div[1]</value>
      <webElementGuid>e94649e7-2791-4cf5-9258-7f43a92da39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop now'])[1]/preceding::div[2]</value>
      <webElementGuid>153c984d-b209-4edb-97a3-bed2cb619c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enfamil Shop']/parent::*</value>
      <webElementGuid>d63cf997-9c7f-4f0c-9436-170c11f1d68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>917bb91e-23b1-4b5a-804e-09352ca190b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Enfamil Shop' or . = 'Enfamil Shop')]</value>
      <webElementGuid>28c0b10a-9933-4924-81bc-73772f32ec10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
