<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Featured</name>
   <tag></tag>
   <elementGuidId>eb29efd9-9a62-48ef-b41f-b6d91124754a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'Featured' or . = 'Featured')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slideshow-picker__tab-nav-item-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@class='slideshow-picker__tab-nav-item-button'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>00048102-381f-47a0-8a26-3eead705a4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slideshow-picker__tab-nav-item-text</value>
      <webElementGuid>0a6daa7f-723c-4fda-9ea8-f6e8f082fcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Featured</value>
      <webElementGuid>a8a10280-acd2-4167-b04c-3779fcff074f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app CoreHomePage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid content-grid--main&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row content-grid--full-width  categories-tab categories-tab--center list-child-pages-cards zindex-2 page-border-radius&quot;]/div[@class=&quot;content-grid__column list-child-pages-image-bottom-right margin-bottom-xxlarge hide-filter-pagination content-grid__column--size-12&quot;]/div[@class=&quot;grid-wrapper slideshow-picker slideshow-picker--tab&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/ul[@class=&quot;slideshow-picker__tab-nav&quot;]/li[@class=&quot;slideshow-picker__tab-nav-item slideshow-picker__tab-nav-item--active&quot;]/button[@class=&quot;slideshow-picker__tab-nav-item-button&quot;]/div[@class=&quot;slideshow-picker__tab-nav-item-text&quot;]</value>
      <webElementGuid>e8e9a4a6-1b7f-4755-8857-f1d970136e10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[8]/div/div[2]/div/div/ul/li/button/div</value>
      <webElementGuid>f28be2a5-2efe-45bb-b65e-2808864ff945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore the full range of Enfamil products.'])[1]/following::div[4]</value>
      <webElementGuid>b2bc284e-022c-4f4a-b3ba-43163a65fc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Products'])[3]/following::div[4]</value>
      <webElementGuid>46864c5d-ce83-4309-b0e6-392896d28d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ages &amp; Stages'])[1]/preceding::div[1]</value>
      <webElementGuid>539a41f1-f44f-4820-a465-22f84a5a55bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feeding Need'])[1]/preceding::div[2]</value>
      <webElementGuid>da6a3e03-2932-42d0-9f9a-84c05ccc0f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Featured']/parent::*</value>
      <webElementGuid>85275138-69a0-4b41-b7de-75c461d34750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li/button/div</value>
      <webElementGuid>694a0633-1e23-4958-b196-d9ac2afdca73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Featured' or . = 'Featured')]</value>
      <webElementGuid>f089d358-c8f1-4927-916e-14e615d63e59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
