<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enfamil Shop</name>
   <tag></tag>
   <elementGuidId>f7ec8624-98d3-4fd4-abba-75b390195fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/article/section/div/div[12]/div/div/div/div/div/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.guarantees-promo-content__title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'guarantees-promo-content__title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20d3f9d4-ef08-46a7-b70c-26584058ad1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>guarantees-promo-content__title</value>
      <webElementGuid>48f748d7-2f41-4230-9687-0d6656e5e87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enfamil Shop</value>
      <webElementGuid>f2f66ef9-7932-43c7-9b41-6a400554ffc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app CoreHomePage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid content-grid--main&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row page-border-radius content-grid--full-width guarantees-promo personalization-home-rtb zindex-2&quot;]/div[@class=&quot;content-grid__column no-padding content-grid__column--size-12&quot;]/div[@class=&quot;carousel&quot;]/div[@class=&quot;carousel-item carousel-item--text-only carousel-item--col&quot;]/div[@class=&quot;carousel-item__content-wrapper carousel-item__content-wrapper--above&quot;]/div[@class=&quot;carousel-item__content&quot;]/div[@class=&quot;rte-wrapper&quot;]/div[@class=&quot;rte&quot;]/div[@class=&quot;rte__text carousel-item__description&quot;]/div[@class=&quot;guarantees-promo-heading&quot;]/div[@class=&quot;guarantees-promo-content__title&quot;]</value>
      <webElementGuid>057d7bfe-d98e-46b4-b1a4-e1871956ccc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[12]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>da5c15fb-697b-4345-bfcb-af7cafa01ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load more'])[2]/following::div[12]</value>
      <webElementGuid>927add9c-c99e-488e-8d08-a4e3c16463d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We can help you to understand the difference between excessive, unexplained...'])[1]/following::div[15]</value>
      <webElementGuid>6265a7b2-b4f5-401a-8b3d-e09dc91e1104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Prices you', &quot;'&quot;, 'll love. Products you trust. Convenience you need.')])[1]/preceding::div[1]</value>
      <webElementGuid>41e88b4e-8f45-4cc7-9883-1f95a8751ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop now'])[1]/preceding::div[2]</value>
      <webElementGuid>4d3f57e1-7ed3-4b27-8ee2-bd129887603a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enfamil Shop']/parent::*</value>
      <webElementGuid>6015c524-bc40-4461-aa83-9146fcd69cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>32442bcb-21f3-4911-9b10-3703f41f15db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Enfamil Shop' or . = 'Enfamil Shop')]</value>
      <webElementGuid>afadcf6c-464d-4557-a001-0a7dfa248c4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
