<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_See Our Formulas_image-as-link__image_1</name>
   <tag></tag>
   <elementGuidId>c5235c74-7538-4f2e-b587-adc1e09f4344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@class = 'image-as-link__image'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>20f7a8b8-97ee-4de8-a444-648e821d71f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-as-link__image</value>
      <webElementGuid>173f2e43-1cc4-411d-9844-bf7733199d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d2jiwtuosjkcsj.cloudfront.net/media/cache/6/b/f/3/a/e/6bf3ae2dbf7c542b25ca17b8256d2f1a360772bb.webp</value>
      <webElementGuid>73b67711-bca5-4f6d-804a-f2bd5e00ca78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>872</value>
      <webElementGuid>02cb0937-2187-42b8-889e-303c8719583a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2640</value>
      <webElementGuid>9b9aa24b-5962-421d-a5c2-5b041a1d8ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app CoreHomePage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid content-grid--main&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row content-grid--full-width page-banner zindex-2 page-border-radius&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;image-as-link&quot;]/a[@class=&quot;image-as-link__link link&quot;]/img[@class=&quot;image-as-link__image&quot;]</value>
      <webElementGuid>7a1d9700-c589-4248-bc9f-e456431b665b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[5]/div/div/a/img</value>
      <webElementGuid>c443fe9a-4d36-423e-abf5-fef9c001d788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d2jiwtuosjkcsj.cloudfront.net/media/cache/6/b/f/3/a/e/6bf3ae2dbf7c542b25ca17b8256d2f1a360772bb.webp')]</value>
      <webElementGuid>6ca67aad-adc6-4242-a76b-29a42a7842b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/a/img</value>
      <webElementGuid>6b4dce81-fe05-48e0-a9c7-95f88d055080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d2jiwtuosjkcsj.cloudfront.net/media/cache/6/b/f/3/a/e/6bf3ae2dbf7c542b25ca17b8256d2f1a360772bb.webp']</value>
      <webElementGuid>648f4272-c18b-4136-ae85-40212fd413ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
