<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_See Our Formulas_image-as-link__image</name>
   <tag></tag>
   <elementGuidId>e498feda-a28f-451f-ad51-4fcc96bd2dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@class = 'image-as-link__image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.image-as-link__image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@class = 'image-as-link__image'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e1165a0f-2371-4f89-a592-c35dde80bb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-as-link__image</value>
      <webElementGuid>e7c0d326-c84b-4ff0-9385-a95d5fecd47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d2jiwtuosjkcsj.cloudfront.net/media/cache/6/9/9/2/2/a/69922aa60d2fd4788c85e01a7ffba48ebab0a53d.png</value>
      <webElementGuid>ba679278-04ca-4605-a08c-33a18b54a6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>960</value>
      <webElementGuid>86d9f2bb-b9bb-4e40-9c87-1cf654cd5c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2640</value>
      <webElementGuid>ebab1dbe-342c-4cba-9068-617c469c2bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app CoreHomePage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid content-grid--main&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row content-grid--full-width page-banner zindex-2 page-border-radius&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;image-as-link&quot;]/a[@class=&quot;image-as-link__link link&quot;]/img[@class=&quot;image-as-link__image&quot;]</value>
      <webElementGuid>332fcc5d-9f01-45c1-920f-88fc7275eb4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[3]/div/div/a/img</value>
      <webElementGuid>1c7da6c6-bdee-4a98-b917-1edc88ed8dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d2jiwtuosjkcsj.cloudfront.net/media/cache/6/9/9/2/2/a/69922aa60d2fd4788c85e01a7ffba48ebab0a53d.png')]</value>
      <webElementGuid>fc429a62-be1b-4a7d-8b2c-bfff23d02f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/a/img</value>
      <webElementGuid>27f446ea-b633-4274-a76c-de2754341d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d2jiwtuosjkcsj.cloudfront.net/media/cache/6/9/9/2/2/a/69922aa60d2fd4788c85e01a7ffba48ebab0a53d.png']</value>
      <webElementGuid>95e4d87c-1147-4d39-9d89-06bd199253ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
