<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Help Center</name>
   <tag></tag>
   <elementGuidId>ca473c14-cd9f-4dd4-b66a-d79e4d39d109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;help-center&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Help Center' or . = 'Help Center')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[(text() = 'Help Center' or . = 'Help Center')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>31f07da5-f50e-4ec2-a6c2-e88fce81b729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>7a734c86-64b0-4313-83de-a81f5960f619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-udi</name>
      <type>Main</type>
      <value>umb://document/54bb6e6f389e45e4934db39a679fe3f0</value>
      <webElementGuid>3e0d26d1-d03e-456e-8d5f-8f4804a12459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/help-center/</value>
      <webElementGuid>a33178ad-5804-4f25-8ca3-324aff8bf455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6bf30732-6e19-4cb7-a6d4-5cbef4977fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>help-center</value>
      <webElementGuid>5ae54618-92f6-4aa3-98a5-0688810c3086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Help Center</value>
      <webElementGuid>28c4bc64-c4e2-4153-81df-c2964afba53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app RBStarterKitContentGridPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row content-grid--full-width contact-us&quot;]/div[@class=&quot;content-grid__column page-banner--text-center no-padding content-grid__column--size-12&quot;]/div[@class=&quot;rte-wrapper&quot;]/div[@class=&quot;rte&quot;]/div[@class=&quot;rte__text&quot;]/div[@class=&quot;content-grid contact-us-content-wrapper&quot;]/div[@class=&quot;contact-us-content&quot;]/p[1]/span[1]/a[1]</value>
      <webElementGuid>6abdf323-61b0-43e0-9302-a0d0288cd44f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div/div/div[2]/div/div/div/div/p/span/a</value>
      <webElementGuid>a8dcf343-05a4-462b-91f3-4f14b0195d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Help Center')])[2]</value>
      <webElementGuid>594bc6e3-d6d0-4128-8fda-9d59f30ab496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you for your interest in the Enfamil Family of Formulas™.'])[1]/following::a[1]</value>
      <webElementGuid>7f895bde-f8f8-4eeb-80a7-bbf312a3c410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store locator.'])[1]/preceding::a[1]</value>
      <webElementGuid>c96a53f1-41d7-4f0a-b58a-333fd73ecc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='meadjohnson.com.'])[1]/preceding::a[2]</value>
      <webElementGuid>bfef367e-38fa-43cd-8111-0ce991bca2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/help-center/')])[3]</value>
      <webElementGuid>c5862fce-660e-43fe-b741-48e68e0f0e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>d0dd63f5-b942-478d-b249-e162ef819656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/help-center/' and @title = 'help-center' and (text() = 'Help Center' or . = 'Help Center')]</value>
      <webElementGuid>d90efc7d-87a5-4611-aad7-a25d65067936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
