<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Enfamil Family Beginnings- From pregn_44be5c</name>
   <tag></tag>
   <elementGuidId>cb8d531b-9d3f-4d53-84d4-1611c4f00b0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.form-control__label.form-control__label--checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div[2]/div/div/div[3]/section/div/div/div/section/div/div/div/div/form/section/div/div[2]/div/div[2]/div[2]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__label form-control__label--checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>registerDatasourceDropdownField_EFBREG</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enfamil Family Beginnings® - From pregnancy to toddlerhood with focus on the Enfamil® Family of Formulas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app RBStarterKitContentGridPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row content-grid--full-width page-border-radius&quot;]/div[@class=&quot;content-grid__column my-profile categories-tab categories-tab--centered-container content-grid__column--size-12&quot;]/div[@class=&quot;grid-wrapper slideshow-picker slideshow-picker--mobileDropdownTab&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;slideshow-picker__slide slideshow-picker__slide--active&quot;]/section[@class=&quot;content-grid content-grid--main&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row profile-preferences my-profile--subscriptions&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;login-register-reset__content login-register-reset__content-register&quot;]/form[@class=&quot;form login-register-reset__form register-form&quot;]/section[@class=&quot;content-grid content-grid--login-register-reset__register-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row program-options&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[2]/div[@class=&quot;form-control form-control--feeding-issue form-control--checkbox&quot;]/div[@class=&quot;form-control__options-wrapper&quot;]/div[1]/label[@class=&quot;form-control__label form-control__label--checkbox&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div[2]/div/div/div[3]/section/div/div/div/section/div/div/div/div/form/section/div/div[2]/div/div[2]/div[2]/div/div/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My little one, 01/01/2022'])[1]/following::label[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Program Options'])[2]/following::label[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Enfamil Family Beginnings® - From pregnancy to toddlerhood with focus on the Enfamil® Family of Formulas' or . = 'Enfamil Family Beginnings® - From pregnancy to toddlerhood with focus on the Enfamil® Family of Formulas')]</value>
   </webElementXpaths>
</WebElementEntity>
