<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Babys Due Date or Birth DateWhyRelation_0027c4</name>
   <tag></tag>
   <elementGuidId>1e9cb6fe-ce01-42d8-8df3-eff63ead02a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.content-grid__column.custom-birthdate-tooltip.content-grid__column--size-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[11]/div/div/section/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>effee23a-e3b6-498e-b09b-5289b60a7b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content-grid__column custom-birthdate-tooltip content-grid__column--size-12</value>
      <webElementGuid>0ffb24eb-485c-447d-90db-e87ba28616f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baby's Due Date or Birth DateWhy?Relationship to childRelationship to childSelect oneRelationship to child field is required.How are you currently feeding your little one? (optional)How are you currently feeding your little one? (optional)Select one</value>
      <webElementGuid>2dd6d81d-c51d-46ba-8440-46a7f056a466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app RBStarterKitContentGridPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row content-grid--full-width offers-drive margin-bottom-xxlarge&quot;]/div[@class=&quot;content-grid__column no-padding content-grid__column--size-12&quot;]/div[@class=&quot;consumer-form&quot;]/div[@class=&quot;consumer-form__form&quot;]/form[@class=&quot;consumer-form__form&quot;]/section[@class=&quot;content-grid content-grid--consumer-form__form-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;child-container&quot;]/section[@class=&quot;content-grid content-grid--child-container&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row form-control--relation&quot;]/div[@class=&quot;content-grid__column custom-birthdate-tooltip content-grid__column--size-12&quot;]</value>
      <webElementGuid>6686c549-917c-40d8-93ba-e997ec47c726</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[11]/div/div/section/div/div/div</value>
      <webElementGuid>08ef47f2-b39f-480a-869e-c0ffffa97d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We’ll provide tips and samples to fit your needs.'])[1]/following::div[6]</value>
      <webElementGuid>1f9dbd76-52bb-488c-a93a-603060f1c74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile phone (optional)'])[1]/following::div[19]</value>
      <webElementGuid>4be026ec-41d9-496d-8c29-0e398db2bd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/section/div/div/div</value>
      <webElementGuid>f7c0d629-e179-475d-99ae-d4ded9ffe6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Baby&quot; , &quot;'&quot; , &quot;s Due Date or Birth DateWhy?Relationship to childRelationship to childSelect oneRelationship to child field is required.How are you currently feeding your little one? (optional)How are you currently feeding your little one? (optional)Select one&quot;) or . = concat(&quot;Baby&quot; , &quot;'&quot; , &quot;s Due Date or Birth DateWhy?Relationship to childRelationship to childSelect oneRelationship to child field is required.How are you currently feeding your little one? (optional)How are you currently feeding your little one? (optional)Select one&quot;))]</value>
      <webElementGuid>f4d463af-740b-4377-a337-69882e97114d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
