<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>First Name field</name>
   <tag></tag>
   <elementGuidId>5caca95d-176f-4cfe-a2c2-291212ee2cc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22806_registerGivenNameField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='form-control form-control--given-name form-control--active']/input[@placeholder='First name*']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adef7eca-a54a-4191-bcb4-6156cbe7a964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--given-name</value>
      <webElementGuid>a471e211-c2df-4ee5-a754-a85aa000d46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22806_registerGivenNameField</value>
      <webElementGuid>c11942ad-1069-4e8f-b375-d395434e5596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registerGivenNameField</value>
      <webElementGuid>f609a336-1376-4aa7-8891-f248de9c673f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First name*</value>
      <webElementGuid>9b387829-7a4d-4fc9-9ed5-01ce258fc461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7bc54976-9928-44b8-8d5d-9773e23726da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>498d117a-0e2f-4b33-8d2a-5603e680e459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Enfamil</value>
      <webElementGuid>3f370101-d974-4b43-9876-c3be19611bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22806_registerGivenNameField&quot;)</value>
      <webElementGuid>3b5bd936-dced-4566-b804-64e66093b0b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='22806_registerGivenNameField']</value>
      <webElementGuid>21c0ec6b-c1e8-4d61-97e0-adce3f86db98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div[2]/div/div/div/section/div/div/div/section/div/div/div/div/form/section/div/div/div/div/input</value>
      <webElementGuid>49b3809b-5e02-4cfc-8fc0-607d7d6a8cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8018b10d-3a26-4674-acf6-1468a211b6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '22806_registerGivenNameField' and @name = 'registerGivenNameField' and @placeholder = 'First name*' and @type = 'text']</value>
      <webElementGuid>3f3cfbef-5d06-4d1b-acd4-b4db1108860a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
