<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Last Name field</name>
   <tag></tag>
   <elementGuidId>10e1de70-13b4-4b3b-b617-f03102592859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22806_registerFamilyNameField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='form-control form-control--family-name form-control--active']/input[@placeholder='Last name*']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fefb0ef-5eba-427d-9df8-a992aa07c246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--family-name</value>
      <webElementGuid>c8af8a77-012d-4f5b-886a-c0e64a1ccfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22806_registerFamilyNameField</value>
      <webElementGuid>a17cf85a-7dd6-4851-aee6-fbc54db7437c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registerFamilyNameField</value>
      <webElementGuid>8f4ed8e9-63c2-46bc-bebd-0735334c6671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last name*</value>
      <webElementGuid>6cb09db2-0e1d-4803-9e2c-e0c7dcc1bd47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c9f685b4-10b3-4068-9e27-6b88961fd460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>992d1a1b-e165-48a2-9e03-b013deab7319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Automation</value>
      <webElementGuid>92f11623-77d9-42d8-8e85-19bfcef328c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22806_registerFamilyNameField&quot;)</value>
      <webElementGuid>87e077cb-b45e-438b-8cab-8cdc47522e18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='22806_registerFamilyNameField']</value>
      <webElementGuid>101f3bcd-70ed-48cb-9795-a34818942227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div[2]/div/div/div/section/div/div/div/section/div/div/div/div/form/section/div/div/div[2]/div/input</value>
      <webElementGuid>ffb61434-46a1-44cf-b222-f26fd3176930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>4eb7e850-3b33-42e2-8743-4bc31437b18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '22806_registerFamilyNameField' and @name = 'registerFamilyNameField' and @placeholder = 'Last name*' and @type = 'text']</value>
      <webElementGuid>c84153c8-5f4c-4267-9a26-1147ff8cc05d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
