<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WIC section</name>
   <tag></tag>
   <elementGuidId>0765fec0-3e06-4766-bbb2-85abb43ffb80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerRadiobuttonListField__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='registerRadiobuttonListField__label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b77b1ba3-6070-45f3-9b0e-f6a9a777385e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__label form-control__label--radio-group</value>
      <webElementGuid>8e41c331-3c82-4107-98e8-cc3f93b13227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>registerRadiobuttonListField</value>
      <webElementGuid>fa5cd704-5133-47c1-8e4c-3f7f00ace9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerRadiobuttonListField__label</value>
      <webElementGuid>e55e5a50-1c95-4afe-b5b0-a6c76edcff56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I expect to receive infant formula from the government sponsored Womens, Infants and the Childrens program (which refers itself WIC)</value>
      <webElementGuid>299e3202-c1d3-442d-bedb-f9a206cf4fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerRadiobuttonListField__label&quot;)</value>
      <webElementGuid>a236ca0f-cb1b-4823-82e3-625f1e7092dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='registerRadiobuttonListField__label']</value>
      <webElementGuid>0353a8a7-8969-4143-8d80-daa3265f14e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registerRadiobuttonListField']/label</value>
      <webElementGuid>2640f02f-0ff6-49a0-9083-954fcc942615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country Code'])[1]/following::label[1]</value>
      <webElementGuid>eecd5255-4666-44f9-9f5d-c0fd5850c43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip Code'])[1]/following::label[2]</value>
      <webElementGuid>00810a20-5a3a-4172-b6ba-d86875057318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::label[1]</value>
      <webElementGuid>d4c54feb-3f76-4583-8297-fc5020311947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::label[2]</value>
      <webElementGuid>78bd7e1f-2607-4358-9ff2-a9cba85723a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I expect to receive infant formula from the government sponsored Womens, Infants and the Childrens program (which refers itself WIC)']/parent::*</value>
      <webElementGuid>023456d4-15d9-4e22-bce9-e7477f290883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/label</value>
      <webElementGuid>48756796-3e3f-45dd-9fd0-22c78ba7b5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'registerRadiobuttonListField__label' and (text() = 'I expect to receive infant formula from the government sponsored Womens, Infants and the Childrens program (which refers itself WIC)' or . = 'I expect to receive infant formula from the government sponsored Womens, Infants and the Childrens program (which refers itself WIC)')]</value>
      <webElementGuid>7286721c-1d59-4d14-9307-e2580604713d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
