<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WIC_No</name>
   <tag></tag>
   <elementGuidId>d3857620-4893-473f-87d5-aed5a2183486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='form-control__radio-option']/label/div[text()='No']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8c6b88de-ec09-4f75-ad56-687de647ea97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__radio-option</value>
      <webElementGuid>b7a914da-5244-47bc-b755-1a01e84140e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>cbd0d28f-88df-4ca6-a192-5e577c14cb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerRadiobuttonListField&quot;)/div[@class=&quot;form-control form-control--radio&quot;]/div[@class=&quot;form-control__options-wrapper&quot;]/div[@class=&quot;form-control__radio-option&quot;]</value>
      <webElementGuid>b6ca5ca9-c40c-4486-a980-2cfb47a8c99f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registerRadiobuttonListField']/div/div/div[2]</value>
      <webElementGuid>a6709610-7f1c-4e50-baf9-761f9b2631b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::div[1]</value>
      <webElementGuid>8bd9152a-f0dc-417b-8f25-f413254609bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country Code'])[1]/following::div[8]</value>
      <webElementGuid>38512ce7-f4c8-4fa3-b799-b50132918a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Sure'])[1]/preceding::div[2]</value>
      <webElementGuid>26e70633-27fb-4eb6-a6a0-b56bfc1952cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]</value>
      <webElementGuid>e9e92c85-6b49-4bcf-bca7-498feb9a4d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'No' or . = 'No')]</value>
      <webElementGuid>1934a25f-c38c-4899-86b2-09f38c57354b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
