<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify password placeholder text for input field</name>
   <tag></tag>
   <elementGuidId>760dae6d-6fe5-4574-8062-8a846cdc1ace</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = '866a7dab-8bf6-4bee-a159-526528536578']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#866a7dab-8bf6-4bee-a159-526528536578_474</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Password*']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9d7cd14-b288-4dd4-8873-d60a021abba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--password</value>
      <webElementGuid>9c65bd4b-f7df-4b86-a7fb-6b7475fb6eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>866a7dab-8bf6-4bee-a159-526528536578_474</value>
      <webElementGuid>40afdbe7-b48a-46fa-a715-5414ab334e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>866a7dab-8bf6-4bee-a159-526528536578</value>
      <webElementGuid>9f328abf-76c1-4444-8745-d3d7346d2100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password*</value>
      <webElementGuid>d377d422-903f-450a-9e66-84bf517c2cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1defc29a-a51c-47b6-9d59-57193cb635ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7aa6c761-2c65-4a92-89b3-5cdae155513f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;866a7dab-8bf6-4bee-a159-526528536578_474&quot;)</value>
      <webElementGuid>417bef7e-1faf-40a4-9c96-5297e1dd6e3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='866a7dab-8bf6-4bee-a159-526528536578_474']</value>
      <webElementGuid>44c530b6-321b-42ae-aeef-107284adc148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[7]/div/div/div/div/input</value>
      <webElementGuid>010e7b1d-f691-4e85-93d4-d0ece369f38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/input</value>
      <webElementGuid>b89aa533-b3f3-4d6b-97a0-a2d5f0bbbe99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '866a7dab-8bf6-4bee-a159-526528536578_474' and @name = '866a7dab-8bf6-4bee-a159-526528536578' and @placeholder = 'Password*' and @type = 'password']</value>
      <webElementGuid>0d7c653a-4b74-4e30-8508-f2e5b1d69a19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
