<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify UnitSuiteApt placeholder text for input field</name>
   <tag></tag>
   <elementGuidId>a4917a17-9331-451c-9ebe-1d674e79f014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'c2ceb8f5-0157-4197-b08b-c2bb5b155899']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2ceb8f5-0157-4197-b08b-c2bb5b155899_509</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Unit/Suite/Apt (optional)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2e478d7-3d9d-4d20-bbd2-1d2eba5b369f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--address</value>
      <webElementGuid>a6352141-d498-49c1-b309-5c7bfd279d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2ceb8f5-0157-4197-b08b-c2bb5b155899_509</value>
      <webElementGuid>9db95aab-c734-4a01-ac6e-894d707fb804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c2ceb8f5-0157-4197-b08b-c2bb5b155899</value>
      <webElementGuid>5508a5fa-c211-4c10-86e3-dfe8f0e8980b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Unit/Suite/Apt (optional)</value>
      <webElementGuid>849de868-4e57-4446-ae8d-818e581e3a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc216f61-34bb-488b-bf9a-3a8cfd26e788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2ceb8f5-0157-4197-b08b-c2bb5b155899_509&quot;)</value>
      <webElementGuid>5d075a91-2ab0-457e-a053-e834e2ce546f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c2ceb8f5-0157-4197-b08b-c2bb5b155899_509']</value>
      <webElementGuid>0a11ddec-765b-4e1b-8a61-39a13672c225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[5]/div/div/section/div/div/div[2]/div/input</value>
      <webElementGuid>61e0d0cd-54ab-4d87-8b33-463aca5b169a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/div/div[2]/div/input</value>
      <webElementGuid>0c6a6e3d-ad44-4c94-a8c3-d5db90f0d8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'c2ceb8f5-0157-4197-b08b-c2bb5b155899_509' and @name = 'c2ceb8f5-0157-4197-b08b-c2bb5b155899' and @placeholder = 'Unit/Suite/Apt (optional)' and @type = 'text']</value>
      <webElementGuid>7582b91e-4dac-42e9-b6fb-0312631ea0a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
