<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify First Name placeholder text for input field</name>
   <tag></tag>
   <elementGuidId>05799790-ee18-48f0-8e53-ed43d810ddda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'First name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fb93a681-abac-454b-96d8-6b50fed6cfd5_824</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='First name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34b3a03b-a845-4090-9fae-6f3abbed009a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--given-name</value>
      <webElementGuid>ed1cf628-4a59-4d1c-b86e-b58f2216db1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fb93a681-abac-454b-96d8-6b50fed6cfd5_824</value>
      <webElementGuid>a78f398e-34dd-4a84-ac99-82f67fadf3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fb93a681-abac-454b-96d8-6b50fed6cfd5</value>
      <webElementGuid>34827537-e147-443d-89b3-5e2126a4e019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First name</value>
      <webElementGuid>8d581216-6f84-4185-8c58-6c718753144d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a62ebaa3-9e3e-4107-9330-ce542bbd833f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fb93a681-abac-454b-96d8-6b50fed6cfd5_824&quot;)</value>
      <webElementGuid>efa6956a-4572-4f87-9cba-772ce2527762</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fb93a681-abac-454b-96d8-6b50fed6cfd5_824']</value>
      <webElementGuid>1b637ea2-2b54-4179-b96a-93bdee88092d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[2]/div/div/input</value>
      <webElementGuid>277cb149-f702-49bd-9c45-52499496e393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>58de9562-42e3-49d7-a101-971a86cbf49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fb93a681-abac-454b-96d8-6b50fed6cfd5_824' and @name = 'fb93a681-abac-454b-96d8-6b50fed6cfd5' and @placeholder = 'First name' and @type = 'text']</value>
      <webElementGuid>f077aada-afc6-48a8-a858-d40c344c4cda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
