<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify Phone placehoder text for input field</name>
   <tag></tag>
   <elementGuidId>1870ed4f-04ac-447a-b1b1-6f020f677597</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = '11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9_731</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Mobile phone (optional)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ace3190f-f8ad-402d-b6e7-66fa7c1ca710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--phone</value>
      <webElementGuid>2b2c33c8-3895-4383-9ae3-5b9d710414fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9_731</value>
      <webElementGuid>5d0c9540-4f02-4abd-831a-23919e4a53b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9</value>
      <webElementGuid>a72095cf-ec56-4a59-8ed0-23ddc5020044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile phone (optional)</value>
      <webElementGuid>55b406a9-879c-46c8-956a-331a8e98ef3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>789261df-03e3-4943-89c1-009fe9652b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9_731&quot;)</value>
      <webElementGuid>2a6777a6-a861-4b2d-a7d2-1061a4e4d078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9_731']</value>
      <webElementGuid>03b33caf-f1a2-42c4-b19b-6418f5572359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[9]/div/div/input</value>
      <webElementGuid>94b72541-9a1a-4fc9-bd34-29273e55a69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>fa088b41-ab80-40e5-a489-bcd627fcdd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9_731' and @name = '11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9' and @placeholder = 'Mobile phone (optional)' and @type = 'tel']</value>
      <webElementGuid>b22c91d0-e15f-41ee-917a-17e380ac1bd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
