<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify Email placeholder text for input field</name>
   <tag></tag>
   <elementGuidId>7b188adc-005d-4f92-bef2-a18b9abe8e6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = '9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_734</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14424f7e-0bae-41d5-a59a-f7458bceb391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--login</value>
      <webElementGuid>cf5e1de4-aae5-4de3-9124-54836bbc4a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_734</value>
      <webElementGuid>e45a3c31-5274-4a7d-93c4-5e1e855b6780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a</value>
      <webElementGuid>bca753ea-cb1e-480e-bbf0-cd10744cde9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>5ed30150-1490-4d33-ae59-b151456fd35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4e3abbd6-6c4a-460e-b904-71c10b909cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_734&quot;)</value>
      <webElementGuid>938dbead-e289-4de5-8dae-da36641b647b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_734']</value>
      <webElementGuid>4e0d2202-88a4-44f1-8e9b-ef50e3a2ea81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[3]/div/div/input</value>
      <webElementGuid>3a450e8a-4d28-40cf-a838-07563784fc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>5c653eed-646a-4efb-8b2f-790b56ccee24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_734' and @name = '9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a' and @placeholder = 'Email' and @type = 'email']</value>
      <webElementGuid>30953e07-094d-4c15-b4d7-58c4bddb7b44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
