<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Shipping to AL</name>
   <tag></tag>
   <elementGuidId>bd077b5b-092f-4c5c-b43f-ad5d7ec0cd0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/article/section/div/div[3]/div[2]/div[8]/div[3]/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.shipping-and-instore__content-location</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>199ba8fc-b211-4b50-ba1b-10f67823dab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shipping-and-instore__content-location</value>
      <webElementGuid>581da83b-c3e8-4e61-a538-1a94c9ea9ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shipping to AL?</value>
      <webElementGuid>361c3bb5-688e-47d0-a0ef-fe99d5cc5ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row product-main&quot;]/div[@class=&quot;content-grid__column product-main__info content-grid__column--size-6&quot;]/div[@class=&quot;shipping-and-instore shipping-and-instore--with-location&quot;]/div[@class=&quot;shipping-and-instore__content&quot;]/div[@class=&quot;shipping-and-instore__content-location&quot;]</value>
      <webElementGuid>3745b8ec-36a7-45a9-b700-e75f38df1e16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[3]/div[2]/div[8]/div[3]/div[5]</value>
      <webElementGuid>8aea5cd1-d466-4b36-8408-170d8c48fb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Location'])[1]/following::div[6]</value>
      <webElementGuid>434bbe61-71ee-4867-99da-289ba35de7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find in store'])[1]/following::div[7]</value>
      <webElementGuid>83d5761a-b3f0-47d1-8a6b-9526657f6c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shipping to']/parent::*</value>
      <webElementGuid>a1abd656-1a75-4c7b-aed5-4120ea18f1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]</value>
      <webElementGuid>989e9d8c-6a3e-4f5d-8cb8-e34034f4eb1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Shipping to AL?' or . = 'Shipping to AL?')]</value>
      <webElementGuid>fecbb8f2-feaf-4549-9c0e-0c68ac3262a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
