<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Toggle search box</name>
   <tag></tag>
   <elementGuidId>dca0d1f5-f404-4dbc-abf6-37a5cc3762dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@aria-label = 'Toggle search box']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.search-box__action-item.search-box__action-item--close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Open search box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c1c3a71-20b1-4240-a0e2-377843a5f209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2dcaff36-0df9-488f-9b6b-cedcb68bb19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Toggle search box</value>
      <webElementGuid>c6434893-e294-41f5-9cbb-aa9bb460a57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-box__action-item search-box__action-item--close</value>
      <webElementGuid>b2a02195-6966-4f8e-94d1-3129e8b16414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toggle search box</value>
      <webElementGuid>d00a6bd4-e959-4706-9e7b-167a183e1e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app RBStarterKitContentGridPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/header[@class=&quot;main-header main-header--fixed-mobileOnly&quot;]/div[@class=&quot;main-header__bottom&quot;]/div[@class=&quot;wrapper wrapper--main-header__bottom-items&quot;]/div[@class=&quot;main_header__contents&quot;]/div[@class=&quot;search-box&quot;]/button[@class=&quot;search-box__action-item search-box__action-item--close&quot;]</value>
      <webElementGuid>6b6db09d-f08c-45a6-a88c-a9f0c530c6e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>eca9b0ad-cdf0-44b1-904c-ab4c20a091a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/header/div[3]/div/div[2]/div[2]/button</value>
      <webElementGuid>0c3a55fd-7332-4c7b-bb7c-7001f00f32c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show contact page'])[1]/following::button[1]</value>
      <webElementGuid>6c28a7af-0035-40d1-8a16-33deb78066d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powered By'])[1]/following::button[2]</value>
      <webElementGuid>3a47920f-1632-4771-a56a-f3030168fb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>c4399de8-0d6e-4cb2-b11d-378097eeb4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Toggle search box' or . = 'Toggle search box')]</value>
      <webElementGuid>5a720b47-d235-42ed-a367-38b35044abc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
