<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Contact Us</name>
   <tag></tag>
   <elementGuidId>39085ee4-04d2-465b-a047-7b9fd6c3d2a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.carousel-item__content-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='carousel-item__content']//*[text() = 'Contact Us']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>f74f4bbb-940d-4b5c-b844-dcbf1483cfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carousel-item__content-header</value>
      <webElementGuid>e1a60034-3045-4c1c-a062-d906eb064bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact Us</value>
      <webElementGuid>a58711f1-e902-4c7e-ab86-6c7adf64988d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app RBStarterKitContentGridPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row content-grid--full-width contact-us&quot;]/div[@class=&quot;content-grid__column page-banner--text-center no-padding content-grid__column--size-12&quot;]/div[@class=&quot;carousel&quot;]/div[@class=&quot;carousel-item carousel-item--default carousel-item--col&quot;]/div[@class=&quot;carousel-item__content-wrapper&quot;]/div[@class=&quot;carousel-item__content&quot;]/div[@class=&quot;rte-wrapper&quot;]/div[@class=&quot;rte&quot;]/div[@class=&quot;rte__text carousel-item__description&quot;]/div[@class=&quot;carousel-item__content&quot;]/h2[@class=&quot;carousel-item__content-header&quot;]</value>
      <webElementGuid>b881aeb7-aabb-4520-89d5-309790994e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div/div/div/div/div/div[2]/div[2]/div/div/div/h2</value>
      <webElementGuid>59070610-5974-4663-9ad9-ca7760ad144e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contact-us'])[1]/following::h2[1]</value>
      <webElementGuid>4e269014-09ee-42b3-96f1-aaa5e3b15004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::h2[1]</value>
      <webElementGuid>5b6cce26-60f2-4094-97f8-16c8c89fc9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you for your interest in the Enfamil Family of Formulas™.'])[1]/preceding::h2[1]</value>
      <webElementGuid>936bfbfb-7729-46b6-a436-df5091f50a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>c90c2842-5cc6-4fb5-9693-d1dc9fffc25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Contact Us' or . = 'Contact Us')]</value>
      <webElementGuid>027a94de-6515-4c11-b211-c3b46c99bdf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
