<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close Formula Calculator</name>
   <tag></tag>
   <elementGuidId>5f37377e-b419-4d8b-8328-488a704b387f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@aria-label = 'Close Formula Calculator']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.formula-calculator__close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[81]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ae5f310-2682-4e74-9240-2fa1b16bb83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>612af4e7-6049-4bec-bc03-f61a7225035e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close Formula Calculator</value>
      <webElementGuid>f39dfe56-4945-4351-9805-4d9794b034fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formula-calculator__close</value>
      <webElementGuid>c165fca7-6c60-43a1-aa2c-04f96a4f81fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close Formula Calculator</value>
      <webElementGuid>9aef4404-1c81-4e3b-af83-e4474119bb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page--sticky-nav mouse-click ReactModal__Body--open&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open modal__overlay formula-calculator__overlay&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open modal formula-calculator&quot;]/button[@class=&quot;formula-calculator__close&quot;]</value>
      <webElementGuid>d545f5dd-b90a-4e6f-8d68-52ea74a8cd1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[81]</value>
      <webElementGuid>fb04cc7c-252f-4b44-ad6f-7fb85fe9580c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Preference'])[1]/following::button[1]</value>
      <webElementGuid>42e42f4d-755e-4423-847c-5c21479d3879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Sale'])[1]/following::button[2]</value>
      <webElementGuid>54afd6af-a581-4888-9bad-749523b7a6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formula Calculator'])[1]/preceding::button[1]</value>
      <webElementGuid>6d3081d5-70e5-46f4-8734-7950f538f83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/button</value>
      <webElementGuid>23789804-b048-4307-bce9-11cdf3f09ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Close Formula Calculator' or . = 'Close Formula Calculator')]</value>
      <webElementGuid>42acff5e-bed3-487b-91cc-79f32fabb071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
