<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_20.7 oz Tub (Case of 6) 1.54 per oz190.99</name>
   <tag></tag>
   <elementGuidId>1024141f-0f86-484b-8562-f68f1e943751</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[53]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.product-options__size-button.product-options__size-button--active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ed8e7bb3-2516-4f11-955f-2faf769be491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ba8f83da-8dc9-4f94-a703-27eb6271173a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value> 20.7 oz Tub (Case of 6)$190.99</value>
      <webElementGuid>2be75df3-96ac-4eed-994b-dc5142198ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-options__size-button product-options__size-button--active</value>
      <webElementGuid>d946a5b8-5989-498c-a6a1-8263a7108303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 20.7 oz Tub (Case of 6) $1.54 per oz$190.99</value>
      <webElementGuid>c39e7a21-a729-4ad4-b64e-f2f971ae96b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row product-main&quot;]/div[@class=&quot;content-grid__column product-main__info content-grid__column--size-6&quot;]/div[@class=&quot;product-options__wrapper&quot;]/div[@class=&quot;product-options&quot;]/div[@class=&quot;row product-options__row&quot;]/div[@class=&quot;product-options__content product-options__content--size&quot;]/button[@class=&quot;product-options__size-button product-options__size-button--active&quot;]</value>
      <webElementGuid>7a809f76-09a5-44ec-92d8-034b8e88bfec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[53]</value>
      <webElementGuid>2b8bb96d-0041-4174-b43a-a6a022814308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[2]/div[2]/div[3]/div[3]/div/div[2]/button</value>
      <webElementGuid>ea82666d-76cd-4c64-b989-3e2c94294914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How much do I need?'])[1]/following::button[1]</value>
      <webElementGuid>25437f7f-0b73-4a59-b821-a338eb468d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Can'])[1]/following::button[2]</value>
      <webElementGuid>a53270c5-e16c-4441-b893-c42c16426e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div[2]/button</value>
      <webElementGuid>dcfeec15-ece9-4ccf-92c1-29f60306ab1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' 20.7 oz Tub (Case of 6) $1.54 per oz$190.99' or . = ' 20.7 oz Tub (Case of 6) $1.54 per oz$190.99')]</value>
      <webElementGuid>819468db-38e1-4e32-bf12-0b89d51d38bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
