<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_minerals</name>
   <tag></tag>
   <elementGuidId>2fe52cce-085b-4810-a814-ee4728c8d4b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'nutrition-information__nutrients-header' and (text() = 'minerals' or . = 'minerals')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/article/section/div/div[4]/div/div/div/div[2]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c8683fe4-de28-4783-a85d-19d9b05964ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nutrition-information__nutrients-header</value>
      <webElementGuid>c9be65f0-e62e-4f62-b4fa-9befbbdb0f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>minerals</value>
      <webElementGuid>fb59515c-07a6-414e-b08a-13c986525302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row content-grid--full-width pdp-wrapper--blue-bg animate-row aos-init aos-animate&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;nutrition-information&quot;]/div[@class=&quot;nutrition-information__wrapper&quot;]/div[@class=&quot;nutrition-information__container&quot;]/div[@class=&quot;nutrition-information__nutrients&quot;]/div[@class=&quot;nutrition-information__nutrients-container&quot;]/div[@class=&quot;nutrition-information__nutrients-header&quot;]</value>
      <webElementGuid>26df5b6c-4d9c-4cc7-b1ef-0e15ad87a042</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[4]/div/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>c2848b56-b772-4794-a32c-7fee8cf9c4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LINOLEIC ACID'])[1]/following::div[2]</value>
      <webElementGuid>09d4439d-4457-4957-90d3-8696444a4ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WATER'])[1]/following::div[3]</value>
      <webElementGuid>82c8a38a-2142-46a3-98ca-44f6e9277a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CALCIUM'])[1]/preceding::div[1]</value>
      <webElementGuid>dd7395ca-0268-492e-bdd4-48cf745bc43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PHOSPHORUS'])[1]/preceding::div[2]</value>
      <webElementGuid>153f7831-ecf6-48cb-b09a-1cf11c72ffb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='minerals']/parent::*</value>
      <webElementGuid>cdef6465-8f26-4e9e-a8c9-5e0346859292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>555e4676-fcac-45c6-b728-1dd63767a22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'minerals' or . = 'minerals')]</value>
      <webElementGuid>3e2824bb-f3da-4822-abc2-fc8a1edf4426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
