<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_vitamins</name>
   <tag></tag>
   <elementGuidId>a7ecfbd1-000f-4db2-8382-1bd11c003da7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'nutrition-information__nutrients-header' and (text() = 'vitamins' or . = 'vitamins')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/article/section/div/div[4]/div/div/div/div[2]/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08b89c62-596f-4d55-9881-78f53e1d79ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nutrition-information__nutrients-header</value>
      <webElementGuid>ee5e71f1-52d1-44f2-9d32-dc3bf7a20f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>vitamins</value>
      <webElementGuid>69891832-29c3-4d4c-bc27-757c30a1bd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row content-grid--full-width pdp-wrapper--blue-bg animate-row aos-init aos-animate&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;nutrition-information&quot;]/div[@class=&quot;nutrition-information__wrapper&quot;]/div[@class=&quot;nutrition-information__container&quot;]/div[@class=&quot;nutrition-information__nutrients&quot;]/div[@class=&quot;nutrition-information__nutrients-container&quot;]/div[@class=&quot;nutrition-information__nutrients-header&quot;]</value>
      <webElementGuid>8d5327f9-1b3f-4124-a221-b3c82513963d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[4]/div/div/div/div[2]/div/div[3]/div</value>
      <webElementGuid>5cb9e0ac-dd89-4043-8844-c09cca522426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHLORIDE'])[1]/following::div[2]</value>
      <webElementGuid>4b320cf7-5b45-41d2-92ea-d037a52913e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POTASSIUM'])[1]/following::div[3]</value>
      <webElementGuid>c90f9bdc-cbbc-4abb-a4e1-584977dac8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/preceding::div[1]</value>
      <webElementGuid>90f89b7e-3ad5-41a5-bf0b-ee29109380a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[1]/preceding::div[2]</value>
      <webElementGuid>784e6320-ec09-4bc4-a763-f0d1ce5d826f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='vitamins']/parent::*</value>
      <webElementGuid>c70b3906-35cc-49ef-b555-03c4be8810ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div[3]/div</value>
      <webElementGuid>9c8b0b19-b23b-4f47-9e14-edf9a5127e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'vitamins' or . = 'vitamins')]</value>
      <webElementGuid>457e97ae-15be-4420-ad0c-4775ab12013c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
