<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nutrition for brain building  immune su_bc9e75</name>
   <tag></tag>
   <elementGuidId>9bcdda1e-fdaf-4859-87dd-bb8fcd7f9447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//img[@class = 'product-hero__badge' and @alt = 'Enfamil NeuroPro Infant Formula']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.product-hero__badge</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@class = 'product-hero__badge' and @alt = 'Enfamil NeuroPro Infant Formula'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>66b0ebdf-f863-4924-b621-ba07ebe6ae44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-hero__badge</value>
      <webElementGuid>fd9b4196-52f6-4a43-87fd-7d05457d31a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d2jiwtuosjkcsj.cloudfront.net/media/3232/whattoexpect400x400.png</value>
      <webElementGuid>7f18f046-b3fc-499f-a147-2509d0b35118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Enfamil NeuroPro Infant Formula</value>
      <webElementGuid>3fc81d40-cef7-433b-aa74-3347e2ec1be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row product-main&quot;]/div[@class=&quot;content-grid__column product-main__hero content-grid__column--size-6&quot;]/div[@class=&quot;product-hero&quot;]/div[@class=&quot;product-hero__slider first-slide&quot;]/div[@class=&quot;slider&quot;]/div[@class=&quot;product-hero__images product-hero__images--badges&quot;]/button[@class=&quot;product-hero__images-image&quot;]/div[@class=&quot;product-hero__badge-wrapper&quot;]/img[@class=&quot;product-hero__badge&quot;]</value>
      <webElementGuid>0e04de48-caf1-47d2-9ce2-79397fa7757b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[2]/div/div/div/div[3]/div/button/div/img</value>
      <webElementGuid>3eba7abc-5467-4653-b8c7-e96406976b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Enfamil NeuroPro Infant Formula'])[2]</value>
      <webElementGuid>c77e211a-85a6-4b59-9023-83ee130bb49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/img</value>
      <webElementGuid>b75c8399-350b-46c4-b310-46c04191ccab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d2jiwtuosjkcsj.cloudfront.net/media/3232/whattoexpect400x400.png' and @alt = 'Enfamil NeuroPro Infant Formula']</value>
      <webElementGuid>c1f68978-36fe-4d1f-bb52-0e3c838e1177</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
