<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_For fussiness, crying, gas and spit-up__bc70d2</name>
   <tag></tag>
   <elementGuidId>a7bb31ea-a142-400f-8a22-5ecc0187380f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@alt = 'Enfamil NeuroPro Gentlease Infant Formula']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/article/section/div/div[8]/div/div[2]/div/div/div[2]/ul/li/div/div/div/a/div/div[2]/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.product-item__image-flip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>03a1da81-545a-47ba-99fc-ff4df06737fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-item__image-flip</value>
      <webElementGuid>3804e201-d62c-489f-8843-e784de36bf90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://metafields-manager-by-hulkapps.s3-accelerate.amazonaws.com/uploads//1648758056-1631716866-hover_Img.png</value>
      <webElementGuid>c79a65d9-5997-4dad-9cf9-43b974821e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Enfamil NeuroPro Gentlease Infant Formula</value>
      <webElementGuid>2a839c5a-5279-4ba0-a666-32f7320ed144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row margin-top-tiny content-grid--full-width personalization-featured-products-pdp shop-category animate-row aos-init aos-animate&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;related-products&quot;]/div[@class=&quot;related-products__content product-list&quot;]/div[@class=&quot;slider slider--less-items&quot;]/div[@class=&quot;slider-frame&quot;]/ul[@class=&quot;slider-list&quot;]/li[@class=&quot;slider-slide slide-visible slide-current&quot;]/div[@class=&quot;col product-list__products&quot;]/div[@class=&quot;col product-item product-item--shopify product-item--visible product-item--family&quot;]/div[@class=&quot;row product-item__content&quot;]/a[@class=&quot;product-item__link product-item__link--with-promotion link&quot;]/div[@class=&quot;col product-item__hero&quot;]/div[@class=&quot;product-item__wrapper product-item__wrapper-flip&quot;]/img[@class=&quot;product-item__image-flip&quot;]</value>
      <webElementGuid>e5f17f47-780f-4c6e-a845-bd9ce5059764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[8]/div/div[2]/div/div/div[2]/ul/li/div/div/div/a/div/div[2]/img[2]</value>
      <webElementGuid>e465f824-411e-4d9c-8c37-4f0483b47544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Enfamil NeuroPro Gentlease Infant Formula'])[3]</value>
      <webElementGuid>309f21c8-d54f-42d9-b99a-15d53edae14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>cefd0624-cf97-40e3-a46a-52bba6303ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://metafields-manager-by-hulkapps.s3-accelerate.amazonaws.com/uploads//1648758056-1631716866-hover_Img.png' and @alt = 'Enfamil NeuroPro Gentlease Infant Formula']</value>
      <webElementGuid>e5763331-a5b8-49d2-b137-e702398ec316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
