<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_How many ounces of formula do you giv_84ec02</name>
   <tag></tag>
   <elementGuidId>ed2b131b-1956-48cb-9e50-db13b4f57d70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'form__input--text' and @id = 'totalVolume']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#totalVolume</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='totalVolume']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb411cd7-1123-48e0-8231-edd7a52da44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input--text</value>
      <webElementGuid>e279c252-2162-4b69-949d-8648e54772fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebdfe6d8-023c-439c-9056-66e8830f8561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[1-9]|[1-3][0-9]|[4][0]</value>
      <webElementGuid>6ef4fd51-346c-4a43-ae6e-2be6794c5141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>06ce0792-0f5a-472e-a396-52d37113fb96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>totalVolume</value>
      <webElementGuid>2b575a80-d0b3-4262-bbf6-52a2f5e412ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter a number from 1 to 40</value>
      <webElementGuid>9091ac68-93f5-4493-8caa-07ece7fabeb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>6798ded4-b28e-464d-9f57-fe37cee2618c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totalVolume&quot;)</value>
      <webElementGuid>631851b1-6165-4d02-94d8-1d363d9dc4c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='totalVolume']</value>
      <webElementGuid>987d46e2-372b-4ce9-8632-300941c6a26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>315302d8-801a-4ae2-aa38-eda1cfc11741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'totalVolume' and @title = 'Enter a number from 1 to 40' and @placeholder = 'Amount']</value>
      <webElementGuid>49f157cb-c044-4389-ad77-36b8d3caa07f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
