<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Compare</name>
   <tag></tag>
   <elementGuidId>d74bbd57-6309-45bb-90ff-1691708a0325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'Compare' or . = 'Compare')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/article/section/div/div[8]/div/div[2]/div/div/div[2]/ul/li/div/div/div/a/div[5]/a[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.product-item__compare.link > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>daaf490b-a5b8-448d-ad0b-1ff573cacd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compare</value>
      <webElementGuid>0b61e39d-19f2-49e2-92f4-10d98025eb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app huskyShopPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row margin-top-tiny content-grid--full-width personalization-featured-products-pdp shop-category animate-row aos-init aos-animate&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;related-products&quot;]/div[@class=&quot;related-products__content product-list&quot;]/div[@class=&quot;slider slider--less-items&quot;]/div[@class=&quot;slider-frame&quot;]/ul[@class=&quot;slider-list&quot;]/li[@class=&quot;slider-slide slide-visible slide-current&quot;]/div[@class=&quot;col product-list__products&quot;]/div[@class=&quot;col product-item product-item--shopify product-item--visible product-item--family&quot;]/div[@class=&quot;row product-item__content&quot;]/a[@class=&quot;product-item__link product-item__link--with-promotion link&quot;]/div[@class=&quot;product-item__actions&quot;]/a[@class=&quot;product-item__compare link&quot;]/span[1]</value>
      <webElementGuid>c45728e2-27f2-4461-91ea-12be72489e96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section/div/div[8]/div/div[2]/div/div/div[2]/ul/li/div/div/div/a/div[5]/a[2]/span</value>
      <webElementGuid>cbcf39a0-c2ac-4ca0-b034-45e4e166c36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[1]/following::span[1]</value>
      <webElementGuid>75ff3783-a455-47e9-ad2e-0f1188a63825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$22.49'])[1]/following::span[2]</value>
      <webElementGuid>bd3d07b9-4481-40fe-822f-d782db6e6246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For sensitive tummies.'])[1]/preceding::span[1]</value>
      <webElementGuid>6a1a3e7b-1fc9-431d-90a5-77fa947988b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More formats &amp; sizes available'])[2]/preceding::span[2]</value>
      <webElementGuid>9d059911-8f24-4cb0-b59f-f4a1cf6819c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compare']/parent::*</value>
      <webElementGuid>ff36dc36-4625-469e-b901-747129cd75e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>efa532c1-5559-436f-a7db-2b37ead4e833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Compare' or . = 'Compare')]</value>
      <webElementGuid>7855e1d0-dbc2-4198-8a11-69ab72071472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
