<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify First Name placeholder text for input field</name>
   <tag></tag>
   <elementGuidId>325084b3-89b0-44ef-898c-a9799f0aa384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='First name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fb93a681-abac-454b-96d8-6b50fed6cfd5_824</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'First name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc35b2d1-eb55-44da-a234-90e674aa12c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--given-name</value>
      <webElementGuid>c0fecf5d-8604-401a-af57-786ce48cc955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fb93a681-abac-454b-96d8-6b50fed6cfd5_824</value>
      <webElementGuid>02f4de99-5a69-44d0-9975-e45dfb1b755e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fb93a681-abac-454b-96d8-6b50fed6cfd5</value>
      <webElementGuid>2aed7865-d252-4907-a760-d7117c4c3f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First name</value>
      <webElementGuid>1c200365-4988-4769-b436-c04a565373dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d85712fb-1b46-4d9c-8e88-eb33e28ed57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fb93a681-abac-454b-96d8-6b50fed6cfd5_824&quot;)</value>
      <webElementGuid>1d5b394a-1087-4a94-bc9e-e4bc74abd2fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fb93a681-abac-454b-96d8-6b50fed6cfd5_824']</value>
      <webElementGuid>fdd031a1-e14c-43af-96ab-700076ba6c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[2]/div/div/input</value>
      <webElementGuid>0131488f-c197-4bef-8662-3d1d9b584360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d4fa9e49-f888-4a90-8dda-20916a1e724b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fb93a681-abac-454b-96d8-6b50fed6cfd5_824' and @name = 'fb93a681-abac-454b-96d8-6b50fed6cfd5' and @placeholder = 'First name' and @type = 'text']</value>
      <webElementGuid>5538bc70-99e9-4853-adb2-1bc3ac850682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
