<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify Phone placehoder text for input field</name>
   <tag></tag>
   <elementGuidId>fcb30310-50a9-4248-a6cf-bd3d3870efa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Mobile phone (optional)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9_731</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = '11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fe820a9-6a57-45b6-914b-2a99a8739115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--phone</value>
      <webElementGuid>b9109ed4-6266-4e0a-a400-1f87ba316acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9_731</value>
      <webElementGuid>4e9516e3-5367-4477-ba23-8511a64a4600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9</value>
      <webElementGuid>90184d10-bb9b-4edc-89b4-f0fca6a24557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile phone (optional)</value>
      <webElementGuid>51dcf55d-87d9-47c9-8c5e-f7193a3a87e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>77cee321-a663-4f5d-9805-87a1d9fede8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9_731&quot;)</value>
      <webElementGuid>eaf5e629-ecc0-45ba-8b78-5aabad5d69d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9_731']</value>
      <webElementGuid>a1d7c06c-7bde-437d-b4bf-f9a4cc269d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[9]/div/div/input</value>
      <webElementGuid>60b58391-96b1-4ebc-be96-8e0b4adc0a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>3a75b7a3-6672-43ab-89cd-0f351cb47ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9_731' and @name = '11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9' and @placeholder = 'Mobile phone (optional)' and @type = 'tel']</value>
      <webElementGuid>e57fc05c-f8c8-4dc8-b97c-ecc743d5ce63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
