<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify Last Name placeholder text for input field</name>
   <tag></tag>
   <elementGuidId>9ceb3d38-50ff-44ca-8154-26333f6c0c9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Last name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f79d7000-6316-40fb-a3e6-b1fa3d3d39f3_81</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'f79d7000-6316-40fb-a3e6-b1fa3d3d39f3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d32b580f-6639-49c7-b399-4d48d3e5c4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--family-name</value>
      <webElementGuid>b4dcfc8d-feda-4ddd-99f3-1ca93abbfc34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f79d7000-6316-40fb-a3e6-b1fa3d3d39f3_81</value>
      <webElementGuid>14fe09f8-6f58-477a-9bad-ec2dd014783b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f79d7000-6316-40fb-a3e6-b1fa3d3d39f3</value>
      <webElementGuid>be1f8bbd-185c-4cd0-83f5-938a2c1caf4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>66b8d1c3-7514-4682-9584-f388683c7953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ba675ab-851b-4abd-b3b8-5a2b31fe3451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f79d7000-6316-40fb-a3e6-b1fa3d3d39f3_81&quot;)</value>
      <webElementGuid>3da23c30-c540-45dc-96bd-1d6f0d9dfec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f79d7000-6316-40fb-a3e6-b1fa3d3d39f3_81']</value>
      <webElementGuid>a66b6d2a-2063-4c21-925e-a5f9facb647d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[2]/div[2]/div/input</value>
      <webElementGuid>ea3cf7b6-9584-4f92-9b2c-29fbcc978eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0842c1e7-39ac-4c87-8656-665661e9d4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f79d7000-6316-40fb-a3e6-b1fa3d3d39f3_81' and @name = 'f79d7000-6316-40fb-a3e6-b1fa3d3d39f3' and @placeholder = 'Last name' and @type = 'text']</value>
      <webElementGuid>bf915671-2253-46c7-9fbe-27336d2d82c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
