<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify Email placeholder text for input field</name>
   <tag></tag>
   <elementGuidId>63be0842-06ce-4543-b083-9ea75581285f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_734</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = '9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1991f906-9b6b-4ea5-828e-fec2095d3675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--login</value>
      <webElementGuid>6cb817c2-3978-4852-b89b-45a4dd9ca29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_734</value>
      <webElementGuid>57342a44-e85e-431c-bd24-f6f72657e00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a</value>
      <webElementGuid>aad0c942-a9ed-4804-9fbb-5f95fa19b695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>c4eb79ab-f146-42ac-81a6-397175620376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2c1daff0-0de7-41fe-a5bd-a5ae05a24e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_734&quot;)</value>
      <webElementGuid>fc090107-c3cb-40ed-b1fc-7d31426123a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_734']</value>
      <webElementGuid>a133d1c3-a7a3-4dad-8225-46de0a28d9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[3]/div/div/input</value>
      <webElementGuid>113f7f51-3388-4ba8-89fb-88dda31cec63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>d71550e9-0e72-4e9d-a5bb-490dbae1765a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a_734' and @name = '9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a' and @placeholder = 'Email' and @type = 'email']</value>
      <webElementGuid>1c2c86be-eddb-47a8-9934-525ac973d727</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
