<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify disclaimer for terms</name>
   <tag></tag>
   <elementGuidId>59b8206f-5936-4e1d-8be5-37f6e4c155cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@class='text-large text-primary margin-bottom-larger']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.terms-condition-desc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>48c08842-b908-47d9-b7b0-768861721b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>terms-condition-desc</value>
      <webElementGuid>82399566-5ffd-44fa-a0d6-caf30785310b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>By clicking “Submit”, I agree to join the Nutramigen Savings and Support program and to receive free samples, offers and other communications from the Nutramigen Savings and Support program and receive other information and offers on family-related health and hygiene products and services from Mead Johnson Nutrition’s affiliated companies. I understand that my information will be shared with such affiliates and will be used in accordance with their own privacy policies. By joining, I acknowledge that I have reviewed and agree to the  Terms of Use and Privacy Policy.</value>
      <webElementGuid>d55feb15-335e-419c-8cd9-eb21593e9713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app RBStarterKitContentGridPage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/main[1]/article[@class=&quot;default-page&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row&quot;]/div[@class=&quot;content-grid__column content-grid__column--size-12&quot;]/div[@class=&quot;rte-wrapper&quot;]/div[@class=&quot;rte&quot;]/div[@class=&quot;rte__text&quot;]/p[@class=&quot;terms-condition-desc&quot;]</value>
      <webElementGuid>112ef18b-9f38-49ed-a665-a236b29562bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[3]/div/div/div/div/p[2]</value>
      <webElementGuid>00adb4a9-79e9-4aaa-820e-bb2960ff6aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::p[2]</value>
      <webElementGuid>0e2b6bb8-d036-4014-819c-7d5cb80caeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not sure'])[1]/following::p[3]</value>
      <webElementGuid>4e00d886-c4ec-4470-840e-17ba71814b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='By clicking “Submit”, I agree to join the']/parent::*</value>
      <webElementGuid>351b9152-dfd0-4250-b9b2-04d072e01e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div[3]/div/div/div/div/p[2]</value>
      <webElementGuid>8bd05fdb-ba69-45ba-b900-12bb9c1033a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'By clicking “Submit”, I agree to join the Nutramigen Savings and Support program and to receive free samples, offers and other communications from the Nutramigen Savings and Support program and receive other information and offers on family-related health and hygiene products and services from Mead Johnson Nutrition’s affiliated companies. I understand that my information will be shared with such affiliates and will be used in accordance with their own privacy policies. By joining, I acknowledge that I have reviewed and agree to the  Terms of Use and Privacy Policy.' or . = 'By clicking “Submit”, I agree to join the Nutramigen Savings and Support program and to receive free samples, offers and other communications from the Nutramigen Savings and Support program and receive other information and offers on family-related health and hygiene products and services from Mead Johnson Nutrition’s affiliated companies. I understand that my information will be shared with such affiliates and will be used in accordance with their own privacy policies. By joining, I acknowledge that I have reviewed and agree to the  Terms of Use and Privacy Policy.')]</value>
      <webElementGuid>3bcb84eb-b765-4bb9-b5cb-819751f870ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
