<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify UnitSuiteApt placeholder text for input field</name>
   <tag></tag>
   <elementGuidId>8d731c89-c572-47c5-ad6d-b0a1ac9a4c5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Unit/Suite/Apt (optional)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2ceb8f5-0157-4197-b08b-c2bb5b155899_509</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'c2ceb8f5-0157-4197-b08b-c2bb5b155899']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50c67512-f062-4022-8e0c-81810a436ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--address</value>
      <webElementGuid>8b56484d-7213-48ab-af2b-712d1b9a23ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2ceb8f5-0157-4197-b08b-c2bb5b155899_509</value>
      <webElementGuid>9b8e4f9f-dc60-4b48-97d3-d3029774e962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c2ceb8f5-0157-4197-b08b-c2bb5b155899</value>
      <webElementGuid>828319eb-7484-4a05-8c32-e1f1c55b38aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Unit/Suite/Apt (optional)</value>
      <webElementGuid>e24dc851-f638-4906-ab34-c32f2eadf855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e2533ff-0f2f-4e13-8e66-b84dfe19dbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2ceb8f5-0157-4197-b08b-c2bb5b155899_509&quot;)</value>
      <webElementGuid>2f6c6e28-ade9-4bd3-92a7-4ef94af18f87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c2ceb8f5-0157-4197-b08b-c2bb5b155899_509']</value>
      <webElementGuid>752abee2-6f6a-4314-848a-fbc6d01a5375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[5]/div/div/section/div/div/div[2]/div/input</value>
      <webElementGuid>685a7b1c-8af8-44cb-865a-d758ede8616e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/div/div[2]/div/input</value>
      <webElementGuid>9ffa83a0-5214-48cf-94af-c051b299d70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'c2ceb8f5-0157-4197-b08b-c2bb5b155899_509' and @name = 'c2ceb8f5-0157-4197-b08b-c2bb5b155899' and @placeholder = 'Unit/Suite/Apt (optional)' and @type = 'text']</value>
      <webElementGuid>185999ca-2542-4c5c-845e-5f2d76a47eab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
