<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify Street address placeholder text for input field</name>
   <tag></tag>
   <elementGuidId>2aab42bf-539d-4829-84f8-f3eaea6ff5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Street address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#65b812a7-bc02-4bcd-ac94-445f25b957b0_117</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = '65b812a7-bc02-4bcd-ac94-445f25b957b0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82128f5e-e4ce-4d55-93c2-bcaec0847478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--address</value>
      <webElementGuid>d9c10755-7304-413f-8260-15d651cde6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>65b812a7-bc02-4bcd-ac94-445f25b957b0_117</value>
      <webElementGuid>91ba08a1-0a02-4c51-9d40-99f1ef0f0d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>65b812a7-bc02-4bcd-ac94-445f25b957b0</value>
      <webElementGuid>a515362c-f388-4768-9bb6-c5e730e08b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>cd46e60d-ef71-4fbc-bedc-55d72c73a44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66cdf679-7c33-4e49-8d7f-b95210d1df30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;65b812a7-bc02-4bcd-ac94-445f25b957b0_117&quot;)</value>
      <webElementGuid>aaf13e88-e467-4b04-bd90-8f50faf476f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='65b812a7-bc02-4bcd-ac94-445f25b957b0_117']</value>
      <webElementGuid>eaa4bf66-6f0f-4c64-88c8-6070fbd6c652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[5]/div/div/section/div/div/div/div/input</value>
      <webElementGuid>72327c01-0d75-46af-b702-609e36e0cb41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/div/div/div/input</value>
      <webElementGuid>ecdc3961-6a20-4f2d-b89b-0809675fe2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '65b812a7-bc02-4bcd-ac94-445f25b957b0_117' and @name = '65b812a7-bc02-4bcd-ac94-445f25b957b0' and @placeholder = 'Street address' and @type = 'text']</value>
      <webElementGuid>9f102f07-e95c-473c-9555-22cc428016a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
