<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>a66df142-cc17-4a0a-9353-129a4a73dbfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq271tb6R5Mi9dmlQYf0HhJ187U9jKo-SeY_pHeaeYQGMF3G3LhhysL6R8jRfTvj6DtAwovkC9VwkNJ184h0d1dqedd9kqelj0ZWVMo-e1ACcBV47-M9ZNzsEuxpR1mATAvrvYkMTZdRNqfh-HfFnCx9kZxpgzovl5KIdbiDgpUGZE9zVWcgR4FIbER4Cb4v-52Zs_56C&amp;k=6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder/Page_ReCAPTCHA demo/iframe_html1body1div3div4iframe1_c-r6i9bofnbiw</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq271tb6R5Mi9dmlQYf0HhJ187U9jKo-SeY_pHeaeYQGMF3G3LhhysL6R8jRfTvj6DtAwovkC9VwkNJ184h0d1dqedd9kqelj0ZWVMo-e1ACcBV47-M9ZNzsEuxpR1mATAvrvYkMTZdRNqfh-HfFnCx9kZxpgzovl5KIdbiDgpUGZE9zVWcgR4FIbER4Cb4v-52Zs_56C&amp;k=6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-')])[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AGdBq271tb6R5Mi9dmlQYf0HhJ187U9jKo-SeY_pHeaeYQGMF3G3LhhysL6R8jRfTvj6DtAwovkC9VwkNJ184h0d1dqedd9kqelj0ZWVMo-e1ACcBV47-M9ZNzsEuxpR1mATAvrvYkMTZdRNqfh-HfFnCx9kZxpgzovl5KIdbiDgpUGZE9zVWcgR4FIbER4Cb4v-52Zs_56C&amp;k=6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-']</value>
   </webElementXpaths>
</WebElementEntity>
