<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Code Activation field</name>
   <tag></tag>
   <elementGuidId>cfbf78b3-4c7a-4256-8219-7e36c243b0f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#29052_74592baf-a945-44e8-85ba-9b5389d9f7cb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='form-control form-control--text']/input[@placeholder='Code Activation*']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64f9ecfe-8645-41db-9917-15ed4ebc3366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--text</value>
      <webElementGuid>6cd833ef-77a8-4505-bd26-ea79c07d02be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>29052_74592baf-a945-44e8-85ba-9b5389d9f7cb</value>
      <webElementGuid>00097e83-bc1a-4727-a809-d67ad6f1c316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>74592baf-a945-44e8-85ba-9b5389d9f7cb</value>
      <webElementGuid>fb9803c5-f8bc-4694-9de0-2378c7935306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code Activation*</value>
      <webElementGuid>02d0579e-ac65-47b6-b4b2-645010560703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8b23705-96ba-4534-b450-98e031abfc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>215e21fd-87b9-4e3c-8710-637c1fd55597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>29052_74592baf-a945-44e8-85ba-9b5389d9f7cb_error</value>
      <webElementGuid>cc4963e7-6a98-4de6-a3eb-7371b78036b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;29052_74592baf-a945-44e8-85ba-9b5389d9f7cb&quot;)</value>
      <webElementGuid>079d98ad-4873-4941-aeba-0bdbd9250d7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='29052_74592baf-a945-44e8-85ba-9b5389d9f7cb']</value>
      <webElementGuid>8be61c61-1a8f-4a5b-8867-9e9a39fe0975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[3]/div/div/div/form/section/div/div[4]/div[2]/div/input</value>
      <webElementGuid>fdf46063-abda-4ef0-bb92-24722fa40e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>e172ac2c-48ec-4c80-811f-8fa7c5669f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '29052_74592baf-a945-44e8-85ba-9b5389d9f7cb' and @name = '74592baf-a945-44e8-85ba-9b5389d9f7cb' and @placeholder = 'Code Activation*' and @type = 'text']</value>
      <webElementGuid>81986d06-f786-4a97-b9c8-6e5880809d15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
