<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify UnitSuiteApt placeholder text for input field</name>
   <tag></tag>
   <elementGuidId>c26005de-3eeb-4119-9ada-c9da7c022f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c2ceb8f5-0157-4197-b08b-c2bb5b155899_509</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'c2ceb8f5-0157-4197-b08b-c2bb5b155899']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Unit/Suite/Apt (optional)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--address</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2ceb8f5-0157-4197-b08b-c2bb5b155899_509</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c2ceb8f5-0157-4197-b08b-c2bb5b155899</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Unit/Suite/Apt (optional)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2ceb8f5-0157-4197-b08b-c2bb5b155899_509&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c2ceb8f5-0157-4197-b08b-c2bb5b155899_509']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[5]/div/div/section/div/div/div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/div/div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'c2ceb8f5-0157-4197-b08b-c2bb5b155899_509' and @name = 'c2ceb8f5-0157-4197-b08b-c2bb5b155899' and @placeholder = 'Unit/Suite/Apt (optional)' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
