<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Father_1</name>
   <tag></tag>
   <elementGuidId>33794d5d-5a6d-4aea-b4ff-d9a7b715fb39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='22207_ec4933e0-1ea5-4110-a00b-3b7aee327760']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.single-select__value-container.single-select__value-container--has-value.css-1hwfws3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6a27006-735f-4d34-a03c-963a6eca1110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>single-select__value-container single-select__value-container--has-value css-1hwfws3</value>
      <webElementGuid>11a0b93d-eac4-491c-af2c-bd74049aab94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Father</value>
      <webElementGuid>6a10b081-ac2f-4909-b878-e4f1ea69bb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22207_ec4933e0-1ea5-4110-a00b-3b7aee327760&quot;)/div[@class=&quot;single-select__control single-select__control--is-focused single-select__control--menu-is-open css-1pahdxg-control&quot;]/div[@class=&quot;single-select__value-container single-select__value-container--has-value css-1hwfws3&quot;]</value>
      <webElementGuid>23d6d39e-1ca8-4b53-be87-8448d1865344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='22207_ec4933e0-1ea5-4110-a00b-3b7aee327760']/div/div</value>
      <webElementGuid>76b315f6-a078-4e7f-8c14-d5795ea48f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship to child'])[2]/following::div[3]</value>
      <webElementGuid>8702425c-e0de-4063-b3f8-b0db45f76a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why?'])[1]/following::div[8]</value>
      <webElementGuid>b7dbeb95-522c-4114-86c1-b882a4eae932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mother'])[1]/preceding::div[4]</value>
      <webElementGuid>c2118861-33d5-4ccf-bac8-d0b2bcf159ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/div/div/div[3]/div/div/div</value>
      <webElementGuid>6dca3e8b-900e-4515-bb37-e03107b6864b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Father' or . = 'Father')]</value>
      <webElementGuid>9e3cc7a6-2ef8-4553-be55-ad9bfd77b37d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
