<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_866a7dab-8bf6-4bee-a159-5265_93e73f</name>
   <tag></tag>
   <elementGuidId>4e8fb6b6-8fb5-4742-a9dc-12b9ccb1d3a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='22207_866a7dab-8bf6-4bee-a159-526528536578']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#22207_866a7dab-8bf6-4bee-a159-526528536578</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>977c7d4a-4ed9-4a89-9ce8-88a278e52ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--password</value>
      <webElementGuid>c34dd85c-40ec-49d6-8911-c35a20bcffe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22207_866a7dab-8bf6-4bee-a159-526528536578</value>
      <webElementGuid>66304273-984b-43f3-a9d0-81c16b551142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>866a7dab-8bf6-4bee-a159-526528536578</value>
      <webElementGuid>7c03e29e-08e9-4899-8f3e-710e50ecdd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password*</value>
      <webElementGuid>bec68f27-fe7f-4e75-9288-12ba4a3a1f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6ee9ef97-d212-44b1-a2f9-dbe09f9e687f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>389fd774-4666-477e-9741-df0d3a4cd193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d2284fcd-e1fb-4ec7-81f8-1a83e572c93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33a71fb9-ffb4-4329-a432-499c1d0d9a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22207_866a7dab-8bf6-4bee-a159-526528536578&quot;)</value>
      <webElementGuid>db173c1c-e39f-4e6d-91c8-94819fac8150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='22207_866a7dab-8bf6-4bee-a159-526528536578']</value>
      <webElementGuid>cba95287-c036-4488-bafd-52b59f4be6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[7]/div/div/div/div/input</value>
      <webElementGuid>cc4e4635-e4bc-4878-aab7-7f6d15edbf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/input</value>
      <webElementGuid>d82de8dd-dbd0-42fa-8beb-2ec95e54a893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '22207_866a7dab-8bf6-4bee-a159-526528536578' and @name = '866a7dab-8bf6-4bee-a159-526528536578' and @placeholder = 'Password*' and @type = 'password']</value>
      <webElementGuid>7dc5463c-eed6-4a1c-8405-89cfef91d23a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
