<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_1cea0cb2-2f5d-4e2d-9c1d-66cd6c282c6c</name>
   <tag></tag>
   <elementGuidId>1c626133-7729-48c7-b0a1-859854d6fae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1cea0cb2-2f5d-4e2d-9c1d-66cd6c282c6c_207</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1cea0cb2-2f5d-4e2d-9c1d-66cd6c282c6c_207']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder = 'City']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--address-city</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1cea0cb2-2f5d-4e2d-9c1d-66cd6c282c6c_207</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1cea0cb2-2f5d-4e2d-9c1d-66cd6c282c6c</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1cea0cb2-2f5d-4e2d-9c1d-66cd6c282c6c_207&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1cea0cb2-2f5d-4e2d-9c1d-66cd6c282c6c_207']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[5]/div/div/section/div/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '1cea0cb2-2f5d-4e2d-9c1d-66cd6c282c6c_207' and @name = '1cea0cb2-2f5d-4e2d-9c1d-66cd6c282c6c' and @placeholder = 'City' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
