<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Step4_Upgrade_products</name>
   <tag></tag>
   <elementGuidId>301f103d-2dd8-49d1-bfe8-7a1131a6e08b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='contentlist__radio-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.contentlist__radio-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contentlist__radio-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choices for BabyNeuroPro GentleaseNeuroPro InfantEnfamom Prenatals D-Vi-Sol Baby VitaminsFussy, Gassy BabyNeuroPro Gentlease X2Enfamom PrenatalsD-Vi-Sol Baby VitaminsInspired by Breast Milk for BabyNeuroPro InfantEnfamom PrenatalsD-Vi-Sol Baby Vitamins</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page--sticky-nav mouse-click ReactModal__Body--open&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open modal__overlay premium-kit-popup signin-wrapper overlay tooltip__overlay&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open modal premium-kit-popup signin-wrapper overlay tooltip&quot;]/section[@class=&quot;overlay-containter welcome-kit-link&quot;]/div[@class=&quot;overlay&quot;]/div[@class=&quot;overlay__content&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row&quot;]/div[@class=&quot;content-grid__column premium-kit-popup content-grid__column--size-12&quot;]/div[@class=&quot;contentlist__radio-container&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick your Premium welcome kit:*'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent Offline'])[1]/following::div[17]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm your choice'])[1]/preceding::div[16]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[3]/preceding::div[20]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/div/div/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Choices for BabyNeuroPro GentleaseNeuroPro InfantEnfamom Prenatals D-Vi-Sol Baby VitaminsFussy, Gassy BabyNeuroPro Gentlease X2Enfamom PrenatalsD-Vi-Sol Baby VitaminsInspired by Breast Milk for BabyNeuroPro InfantEnfamom PrenatalsD-Vi-Sol Baby Vitamins' or . = 'Choices for BabyNeuroPro GentleaseNeuroPro InfantEnfamom Prenatals D-Vi-Sol Baby VitaminsFussy, Gassy BabyNeuroPro Gentlease X2Enfamom PrenatalsD-Vi-Sol Baby VitaminsInspired by Breast Milk for BabyNeuroPro InfantEnfamom PrenatalsD-Vi-Sol Baby Vitamins')]</value>
   </webElementXpaths>
</WebElementEntity>
