<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select oneIm not sureBreast milk and formulaBreast milk onlyFormula only</name>
   <tag></tag>
   <elementGuidId>c67dc73e-133e-427e-a7db-7b474a4a80ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22218_90c3f000-2791-4866-96f4-93adfe64ba39</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='22218_90c3f000-2791-4866-96f4-93adfe64ba39']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ab8bfc7a-62d2-464d-a390-b28cdbccfbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--select</value>
      <webElementGuid>fa3b6585-6b15-4cf8-9e18-650687dfc22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22218_90c3f000-2791-4866-96f4-93adfe64ba39</value>
      <webElementGuid>188ad849-9b9e-43d9-b24d-52297cb1f9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>22218_90c3f000-2791-4866-96f4-93adfe64ba39</value>
      <webElementGuid>ef7b7736-b1b9-46cc-855b-5440a763cde0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select one</value>
      <webElementGuid>4f2a24de-2512-47d3-87c2-7f4a8e4d01d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>How are you currently feeding your little one? (optional): Select one</value>
      <webElementGuid>ed6d5ff6-62ee-445a-be9a-bdffca0d8d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac23051d-ee0d-429e-8fa5-2eb614c2bf30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select oneI'm not sureBreast milk and formulaBreast milk onlyFormula only</value>
      <webElementGuid>c783ebc0-9b2c-423b-9417-5f0b288e558f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22218_90c3f000-2791-4866-96f4-93adfe64ba39&quot;)</value>
      <webElementGuid>b48527b6-c26c-4f76-b30e-e83be48eb8c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='22218_90c3f000-2791-4866-96f4-93adfe64ba39']</value>
      <webElementGuid>90a89c84-717b-4379-98e3-ddbb408c3450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[11]/div/div/section/div/div/div/div[5]/select</value>
      <webElementGuid>7229195a-3167-4fcf-8fa9-25e353c9d8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How are you currently feeding your little one? (optional)'])[1]/following::select[1]</value>
      <webElementGuid>7483e3c8-4b53-4181-a517-1523498eee61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(optional)'])[1]/following::select[1]</value>
      <webElementGuid>4bef1cc8-b2cd-407f-b2ac-7239227b8685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WIC Status'])[1]/preceding::select[1]</value>
      <webElementGuid>58c23f9c-b985-4408-8740-9b54f9034144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::select[1]</value>
      <webElementGuid>bfae5360-65c7-40d1-8f34-fc5487381bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>9c44ff4c-f357-4409-8145-3edcbb376efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '22218_90c3f000-2791-4866-96f4-93adfe64ba39' and @name = '22218_90c3f000-2791-4866-96f4-93adfe64ba39' and @placeholder = 'Select one' and (text() = concat(&quot;Select oneI&quot; , &quot;'&quot; , &quot;m not sureBreast milk and formulaBreast milk onlyFormula only&quot;) or . = concat(&quot;Select oneI&quot; , &quot;'&quot; , &quot;m not sureBreast milk and formulaBreast milk onlyFormula only&quot;))]</value>
      <webElementGuid>8314a261-6ede-4d28-a999-09c4b18b5637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
