<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_North Carolina</name>
   <tag></tag>
   <elementGuidId>a22876bb-08c9-4e6a-8481-46961b0ee927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-5-option-33']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-5-option-33</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a94ec748-e771-4d36-8799-c6ebb13177f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>single-select__option single-select__option--is-focused css-1n7v3ny-option</value>
      <webElementGuid>4a2ab421-a35d-4f12-aabf-dd4aad363de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-5-option-33</value>
      <webElementGuid>335a23d2-28aa-43db-9d47-d69348176464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e5cdf132-68a2-4bb7-914f-0914985d95c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>North Carolina</value>
      <webElementGuid>13e05fa5-b4b5-4c58-977f-df855dcf0361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-5-option-33&quot;)</value>
      <webElementGuid>7bb867ff-4718-44a1-9739-3218477a6627</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-5-option-33']</value>
      <webElementGuid>31dd2406-1d17-4bd0-8aa6-ec73afef9b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='22207_f9acd18e-7be3-472a-9f63-3affc22b70db']/div[2]/div/div[34]</value>
      <webElementGuid>9058b184-17db-4524-9d60-6c7f67a74187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New York'])[1]/following::div[1]</value>
      <webElementGuid>62b0e3d8-420f-4d50-ba16-90c50f7618f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Mexico'])[1]/following::div[2]</value>
      <webElementGuid>e3c0b46d-15f8-4958-b754-b70ff862998f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='North Dakota'])[1]/preceding::div[1]</value>
      <webElementGuid>5fe885a3-eae4-4a2d-9d51-9e0986bcf477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ohio'])[1]/preceding::div[2]</value>
      <webElementGuid>e3962e80-6f1c-492a-8a24-84cb9547a5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='North Carolina']/parent::*</value>
      <webElementGuid>d419aedb-e265-4b7a-960a-016446e8fe48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[34]</value>
      <webElementGuid>36e9aa67-f0f4-4312-94fa-1529f01eb0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-5-option-33' and (text() = 'North Carolina' or . = 'North Carolina')]</value>
      <webElementGuid>a6afd28d-e36c-4ff1-8f2e-cee0fc0595c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
