<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile phone (optional)_11bc8c7d-cb5a_a1e949</name>
   <tag></tag>
   <elementGuidId>6e7e0d11-ee40-4db8-830b-f0caa7664ded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='22207_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#22207_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad206ec6-3646-4625-9691-ebe8032929d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--phone</value>
      <webElementGuid>79bfd06e-3ce3-4ee6-a13e-77eae67504ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22207_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9</value>
      <webElementGuid>138dde34-b223-4174-8ab8-6e3c2071a31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9</value>
      <webElementGuid>802ac9cc-9589-4295-ac23-479e62ab2fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile phone (optional)</value>
      <webElementGuid>73eb9b84-c3ce-42cb-a923-54221418b35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2b30fd8b-7f72-49d5-b9f8-a3a493ff998c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a9a3da5c-d63e-4cfb-9cc5-bf78b6f8050e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>52f1cf03-31df-496d-91ae-60b7451ffd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22207_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9&quot;)</value>
      <webElementGuid>b937bfe5-8eca-4a62-b624-71ad29f7a949</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='22207_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9']</value>
      <webElementGuid>2bd41d70-d2cc-42ac-9490-8dc2b556dd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[9]/div/div/input</value>
      <webElementGuid>3044a18b-761e-461a-9e8f-89f16d9bffad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>9a292c21-3cde-4b83-a961-41e0cd8a9f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '22207_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9' and @name = '11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9' and @placeholder = 'Mobile phone (optional)' and @type = 'tel']</value>
      <webElementGuid>53ac2015-2f81-40a1-986d-9440f2ea16a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
