<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_866a7dab-8bf6-4bee-a159-5265_93e73f</name>
   <tag></tag>
   <elementGuidId>5718281a-cdd7-4a7c-82f9-713ea49c9503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='22207_866a7dab-8bf6-4bee-a159-526528536578']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#22207_866a7dab-8bf6-4bee-a159-526528536578</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44aff9a8-73d2-41a2-9033-83873ae5adda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--password</value>
      <webElementGuid>415ae24e-1e84-4bac-a676-cfdddfa5fa31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22207_866a7dab-8bf6-4bee-a159-526528536578</value>
      <webElementGuid>1e1e3f34-abb3-4901-9ef2-3d7a147b7b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>866a7dab-8bf6-4bee-a159-526528536578</value>
      <webElementGuid>4288954b-f7d0-455a-8f84-940fcf0b9eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password*</value>
      <webElementGuid>81ab78e5-ed94-4263-bc79-56e9cf5f4bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cc1adb26-7111-426a-8c4c-b0d481031a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1a973736-1a3d-434c-9928-d78298b938fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f0d39b5c-eb36-4549-a5c3-c9b7124f0270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c752a71-8e7d-474b-bb51-86179e6480d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22207_866a7dab-8bf6-4bee-a159-526528536578&quot;)</value>
      <webElementGuid>e2a7d9d3-a661-4f6d-a20c-b9a5315c9916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='22207_866a7dab-8bf6-4bee-a159-526528536578']</value>
      <webElementGuid>cba5aa9f-ea9f-4935-91b8-0c2364af451c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[7]/div/div/div/div/input</value>
      <webElementGuid>6913c299-1ea8-44fc-af1b-5b8165f1739c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/input</value>
      <webElementGuid>b0dec0ea-4272-444c-bbec-1eb899629b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '22207_866a7dab-8bf6-4bee-a159-526528536578' and @name = '866a7dab-8bf6-4bee-a159-526528536578' and @placeholder = 'Password*' and @type = 'password']</value>
      <webElementGuid>276ebe09-586d-4992-b636-1d1e74dcc839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
