<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify State placeholder text for dropdown field</name>
   <tag></tag>
   <elementGuidId>490a703d-ff51-47d5-a8ce-d9f3f65c119d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='content-grid__column form-control--state content-grid__column--size-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f9acd18e-7be3-472a-9f63-3affc22b70db</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c748960a-12f6-45a8-8ad7-c41ce1173483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--single-select css-2b097c-container</value>
      <webElementGuid>a6a5f4a4-7729-4a7b-bb12-7169373245a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f9acd18e-7be3-472a-9f63-3affc22b70db</value>
      <webElementGuid>55d63371-b0b5-4590-a5d6-be3ed7c5d2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>State</value>
      <webElementGuid>ed0376b5-fd68-4448-9ce2-da11c6eb9c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f9acd18e-7be3-472a-9f63-3affc22b70db&quot;)</value>
      <webElementGuid>671e0b60-f650-449d-9873-0738a8a091b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='f9acd18e-7be3-472a-9f63-3affc22b70db']</value>
      <webElementGuid>4917b3ae-fd72-4a2b-9310-280a5718b380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[5]/div/div/section/div/div[2]/div[2]/div/div</value>
      <webElementGuid>b22d97ab-4b5b-4b61-a288-0db2d047bb1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::div[1]</value>
      <webElementGuid>c28fb0e5-d5f5-4a7c-93c4-992dd22bc0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City field is required.'])[1]/following::div[3]</value>
      <webElementGuid>0cccde54-4159-4adb-a7f2-b01f9842464f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State field is required.'])[1]/preceding::div[9]</value>
      <webElementGuid>c2b36b69-99e3-4268-b7b1-e5221abf5eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div[2]/div/div</value>
      <webElementGuid>0d99d5a8-67f8-4d69-874c-635936e92b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'f9acd18e-7be3-472a-9f63-3affc22b70db' and (text() = 'State' or . = 'State')]</value>
      <webElementGuid>9dcad2a3-2cd2-4969-a616-a68314bb3d00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
