<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Follow us_social-links__icon social-links_198a1c (1) (1)</name>
   <tag></tag>
   <elementGuidId>9f79865b-fdc0-4302-bbb3-2e5b5de916cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.social-links__icon.social-links__icon--instagram</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//i[@class='social-links__icon social-links__icon--instagram'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7211a7a4-b172-4e7e-8fc7-1582af091b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>social-links__icon social-links__icon--instagram</value>
      <webElementGuid>fc39e8e4-9c7c-458c-a487-b21902a979ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sk-app CoreHomePage hide-page-title&quot;]/div[@class=&quot;page-container page-container--main&quot;]/footer[@class=&quot;main-footer&quot;]/div[@class=&quot;page-container&quot;]/section[@class=&quot;content-grid&quot;]/div[@class=&quot;content-grid__section&quot;]/div[@class=&quot;content-grid__row main-footer__main main-footer__order hide-mobile&quot;]/div[@class=&quot;content-grid__column main-footer__download  content-grid__column--size-4&quot;]/div[@class=&quot;social-links&quot;]/ul[@class=&quot;social-links__elements&quot;]/li[@class=&quot;social-links__element social-links__element--instagram&quot;]/a[@class=&quot;social-links__link social-links__link--instagram link&quot;]/i[@class=&quot;social-links__icon social-links__icon--instagram&quot;]</value>
      <webElementGuid>78f203f3-5225-4160-b86a-f5c6aa38648e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/footer/div/section/div/div/div[2]/div[2]/ul/li/a/i</value>
      <webElementGuid>980906e5-b6bb-4197-839b-8d39dfd3a3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>b461d612-9b2f-4dec-a615-59fe54356f1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
