<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UnitSuiteApt_006fe22a-d7ee-4d57-bfac-_645c72_1</name>
   <tag></tag>
   <elementGuidId>a63b9303-a997-471a-b4af-2119690a7e0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#006fe22a-d7ee-4d57-bfac-27e9851bb7ca_156</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder = 'Unit/Suite/Apt (optional)']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='006fe22a-d7ee-4d57-bfac-27e9851bb7ca_156']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--address</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>006fe22a-d7ee-4d57-bfac-27e9851bb7ca_156</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>006fe22a-d7ee-4d57-bfac-27e9851bb7ca</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Unit/Suite/Apt (optional)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;006fe22a-d7ee-4d57-bfac-27e9851bb7ca_156&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='006fe22a-d7ee-4d57-bfac-27e9851bb7ca_156']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[4]/div/div[2]/div/form/section/div/div[2]/div/div/section/div/div/div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/div/div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '006fe22a-d7ee-4d57-bfac-27e9851bb7ca_156' and @name = '006fe22a-d7ee-4d57-bfac-27e9851bb7ca' and @placeholder = 'Unit/Suite/Apt (optional)' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
