<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile phone (optional)_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9</name>
   <tag></tag>
   <elementGuidId>ba307871-f6b5-4425-a969-0f4cc6b075c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22207_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='22207_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27852637-9809-4a40-8c4a-3a085aaa3551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--phone</value>
      <webElementGuid>96b6dbc2-ac32-44bf-8142-27db24d7debc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22207_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9</value>
      <webElementGuid>bec93394-e008-4720-9b2f-d63e4d391b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9</value>
      <webElementGuid>dddad27c-d82d-48b0-81e4-9d5846dd1d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile phone (optional)</value>
      <webElementGuid>a25e33bc-e7fc-4518-b125-7ced99b384f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>d2606007-376c-46f8-b337-cca9bd24b5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd3d6096-528b-4c34-958f-3865c6992329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22207_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9&quot;)</value>
      <webElementGuid>8c0e1a9f-b154-4040-835b-1b0c2f290cc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='22207_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9']</value>
      <webElementGuid>ae07e167-da52-4f43-8aa5-5efb12946ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[9]/div/div/input</value>
      <webElementGuid>cb3d1f88-6ee9-43b3-b603-64789beadfa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>7ec5e9c0-b7de-4831-89d7-8cfaae600c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '22207_11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9' and @name = '11bc8c7d-cb5a-4e39-95f3-1a213a5ffea9' and @placeholder = 'Mobile phone (optional)' and @type = 'tel']</value>
      <webElementGuid>787ab5f9-bf87-4c7f-8332-c63e32e79dc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
