<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street address</name>
   <tag></tag>
   <elementGuidId>c11a5180-329d-4197-9d66-020310829f4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22207_65b812a7-bc02-4bcd-ac94-445f25b957b0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='22207_65b812a7-bc02-4bcd-ac94-445f25b957b0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6ec1153-a000-42ad-915d-6c67fcd2fea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--address</value>
      <webElementGuid>2a1bf5b4-02de-4878-8500-30dda2f14289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22207_65b812a7-bc02-4bcd-ac94-445f25b957b0</value>
      <webElementGuid>0efeae11-688d-4141-bd9e-30dcb493b84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>65b812a7-bc02-4bcd-ac94-445f25b957b0</value>
      <webElementGuid>87b488d0-5212-49c3-8c89-32a27386dec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>45a2c7d8-ba4a-4ef4-86b5-258be64e79eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e542b0b7-7338-448b-ae1c-b66d35868891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>68fbc465-7f92-44a6-9449-08717987c456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22207_65b812a7-bc02-4bcd-ac94-445f25b957b0&quot;)</value>
      <webElementGuid>0d756855-85d8-4b86-883f-9fea71fb0af9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='22207_65b812a7-bc02-4bcd-ac94-445f25b957b0']</value>
      <webElementGuid>bc70e953-b54c-485a-8f82-7f28d09ab700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[5]/div/div/section/div/div/div/div/input</value>
      <webElementGuid>9c32e9e9-d357-432a-a6ac-ac211aa6c6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/div/div/div/input</value>
      <webElementGuid>7be7af79-2bc9-44d8-88cc-c37c0fd16cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '22207_65b812a7-bc02-4bcd-ac94-445f25b957b0' and @name = '65b812a7-bc02-4bcd-ac94-445f25b957b0' and @placeholder = 'Street address' and @type = 'text']</value>
      <webElementGuid>c887a065-d7b4-4c4d-a13c-10c732eaeae9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
