<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email</name>
   <tag></tag>
   <elementGuidId>b808e6ef-2157-48eb-b678-a50f46a81e17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22207_9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='22207_9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9720fa2f-8588-425d-b4c3-d8cf8b0e872d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--login</value>
      <webElementGuid>d0e4ebe6-d06f-4935-a831-460a27328f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22207_9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a</value>
      <webElementGuid>6d66cc00-c75c-4c21-8071-c70acdccf7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a</value>
      <webElementGuid>215f3b6d-cb0c-4753-b062-4c63fb9d271d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>6956a7fa-d343-40a6-ad15-a34247bcd5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>662de369-ddd9-47ed-9eca-560ed4155d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f603fb3-616b-4acb-9206-20de2cb7f3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22207_9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a&quot;)</value>
      <webElementGuid>020d5b4e-3b50-48e4-ab97-6183c6fdab9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='22207_9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a']</value>
      <webElementGuid>c64ec877-04a0-497e-b9c0-d110e6df720a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[3]/div/div/input</value>
      <webElementGuid>e7c86d2f-e149-4694-9007-bb6d3f64d9f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>901c7de1-731e-4aa2-9467-546f9eae1125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '22207_9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a' and @name = '9fcda2d9-4eb1-44ad-9f84-baea49c9ae6a' and @placeholder = 'Email' and @type = 'email']</value>
      <webElementGuid>4758b3eb-ee92-4a98-8ee4-805bffe64f04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
