<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name</name>
   <tag></tag>
   <elementGuidId>5e371f8d-2d9b-4563-9871-af7bf16bf7ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22207_f79d7000-6316-40fb-a3e6-b1fa3d3d39f3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='22207_f79d7000-6316-40fb-a3e6-b1fa3d3d39f3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06442344-7f86-4234-99a7-8b891c1feab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--family-name</value>
      <webElementGuid>2483efee-0378-4db3-86bf-9ff71f59a58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22207_f79d7000-6316-40fb-a3e6-b1fa3d3d39f3</value>
      <webElementGuid>7e0b5c50-6b2e-4de0-a2c6-0a22981e992a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f79d7000-6316-40fb-a3e6-b1fa3d3d39f3</value>
      <webElementGuid>e5465bd2-5925-49dd-91f9-4e30738137d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>24450f61-029c-4c85-99c9-d0944e0c0762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7612b6d1-de81-4321-906e-fb3a8b2f4bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98e38afb-87b6-4a88-9e5b-d9bd8728f8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22207_f79d7000-6316-40fb-a3e6-b1fa3d3d39f3&quot;)</value>
      <webElementGuid>0db9a58c-0b4a-4a37-9dc4-fe6b86cfeff2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='22207_f79d7000-6316-40fb-a3e6-b1fa3d3d39f3']</value>
      <webElementGuid>ff900d79-8fdc-4394-9448-dda00aa63e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[2]/div[2]/div/input</value>
      <webElementGuid>f05b0974-16fd-425c-ae49-30f35d06e64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e5e9cb94-91df-468b-9ac0-7c4615571487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '22207_f79d7000-6316-40fb-a3e6-b1fa3d3d39f3' and @name = 'f79d7000-6316-40fb-a3e6-b1fa3d3d39f3' and @placeholder = 'Last name' and @type = 'text']</value>
      <webElementGuid>bfc4658a-aea6-4d04-af0e-5176c1bdc802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
