<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UnitSuiteApt (optional)</name>
   <tag></tag>
   <elementGuidId>e8093423-1391-4896-b429-c12d305cb458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22207_c2ceb8f5-0157-4197-b08b-c2bb5b155899</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='22207_c2ceb8f5-0157-4197-b08b-c2bb5b155899']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa283fd9-9b36-48ae-8f66-47c99dfde7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--address</value>
      <webElementGuid>5c60ff8a-c2db-4219-8729-617210e3c4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22207_c2ceb8f5-0157-4197-b08b-c2bb5b155899</value>
      <webElementGuid>ee7afbba-a947-4ef5-afce-d24994cc0205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c2ceb8f5-0157-4197-b08b-c2bb5b155899</value>
      <webElementGuid>1a04d0ee-ca90-40ba-b1ca-17c94489e7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Unit/Suite/Apt (optional)</value>
      <webElementGuid>579ba113-c049-49c4-b7eb-e6696a569dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea248780-6865-4e50-837a-7b771951f469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>57179e4c-cb63-427c-88c3-3f290281273b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22207_c2ceb8f5-0157-4197-b08b-c2bb5b155899&quot;)</value>
      <webElementGuid>68970c7f-f892-4857-9dd8-953c2b150386</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='22207_c2ceb8f5-0157-4197-b08b-c2bb5b155899']</value>
      <webElementGuid>aea369b2-8fbb-4ee4-84bb-0d7e6405216f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[5]/div/div/section/div/div/div[2]/div/input</value>
      <webElementGuid>eb1931c3-1f3b-4ee7-ae74-ae5200a4801a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/div/div[2]/div/input</value>
      <webElementGuid>046705e5-7cfc-4a12-8035-e862fec48c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '22207_c2ceb8f5-0157-4197-b08b-c2bb5b155899' and @name = 'c2ceb8f5-0157-4197-b08b-c2bb5b155899' and @placeholder = 'Unit/Suite/Apt (optional)' and @type = 'text']</value>
      <webElementGuid>a94b5412-017e-4b8f-8b08-7e59cd7c75fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
