<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select oneBreast milk and formulaBreast milk onlyFormula only</name>
   <tag></tag>
   <elementGuidId>be414b96-67cf-40b3-9853-8d83b16e6e89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22207_9143d7ee-4276-4083-84e8-17d7fd629df3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='22207_9143d7ee-4276-4083-84e8-17d7fd629df3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>120ba016-e4b7-406b-99fd-65c7083041a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--select</value>
      <webElementGuid>6dafee97-f076-4e56-9921-c1959a8adedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22207_9143d7ee-4276-4083-84e8-17d7fd629df3</value>
      <webElementGuid>2eaa863a-07a3-4897-9eef-0a3460b28cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>22207_9143d7ee-4276-4083-84e8-17d7fd629df3</value>
      <webElementGuid>9ac33a8c-b1be-46b8-81dc-22562c59062c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select one</value>
      <webElementGuid>6666abfb-e676-48d4-a420-e39feed2a2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>How are you currently feeding your little one? (optional): Select one</value>
      <webElementGuid>6cc9c138-ad0d-4a17-95ef-c9654e06eb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5ef0160-ffa4-4120-81e6-1c207b30cea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select oneBreast milk and formulaBreast milk onlyFormula only</value>
      <webElementGuid>be15900b-fdba-4b15-b33b-aad1caeadd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22207_9143d7ee-4276-4083-84e8-17d7fd629df3&quot;)</value>
      <webElementGuid>c4468ff9-880e-48cf-bbe8-9c3c1b230c45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='22207_9143d7ee-4276-4083-84e8-17d7fd629df3']</value>
      <webElementGuid>fc6f1c03-1f94-4589-82eb-38da263b2550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[11]/div/div/section/div/div/div/div[5]/select</value>
      <webElementGuid>fabc370a-269a-4bc3-a3c4-80786ec39bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How are you currently feeding your little one? (optional)'])[1]/following::select[1]</value>
      <webElementGuid>5e9ecd7f-6be1-4454-97ef-1ff72351689a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(optional)'])[1]/following::select[1]</value>
      <webElementGuid>7e4d302d-641b-49a3-9e53-3bddb0f1df3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::select[1]</value>
      <webElementGuid>98d0ff26-076f-462a-a680-61bb11aacfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::select[1]</value>
      <webElementGuid>d6dcc9cb-c28e-4b0e-8105-690b0588eb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>9df87b4d-7c69-4a40-9094-f9e37226bede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '22207_9143d7ee-4276-4083-84e8-17d7fd629df3' and @name = '22207_9143d7ee-4276-4083-84e8-17d7fd629df3' and @placeholder = 'Select one' and (text() = 'Select oneBreast milk and formulaBreast milk onlyFormula only' or . = 'Select oneBreast milk and formulaBreast milk onlyFormula only')]</value>
      <webElementGuid>fa48de4e-927b-45eb-a8df-b3e7f876c8e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
