<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select oneMotherFatherGrandparentOthers</name>
   <tag></tag>
   <elementGuidId>8eb98af0-83e3-4c6e-86e3-91c5a87d98be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22207_ec4933e0-1ea5-4110-a00b-3b7aee327760</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='22207_ec4933e0-1ea5-4110-a00b-3b7aee327760']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0b6f7a7a-ac54-4b0a-9c6c-e505154e7ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--select</value>
      <webElementGuid>e1f9d27e-ca35-4a39-a388-881eca29ae84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22207_ec4933e0-1ea5-4110-a00b-3b7aee327760</value>
      <webElementGuid>0af7a4cd-726d-41c8-96f9-16d0f3a392d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>22207_ec4933e0-1ea5-4110-a00b-3b7aee327760</value>
      <webElementGuid>db3c2561-3086-4041-8c79-ea16011ec92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select one</value>
      <webElementGuid>b08c3752-1adc-4a48-a0a3-7125692bb8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Relationship to child: Select one</value>
      <webElementGuid>40473be0-a66d-4b4d-832f-9c004c4cceeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e596ad7-ecf6-4978-890f-4908430fc446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select oneMotherFatherGrandparentOthers</value>
      <webElementGuid>4f4f752e-a634-4f1b-bc0e-904505939acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22207_ec4933e0-1ea5-4110-a00b-3b7aee327760&quot;)</value>
      <webElementGuid>9b9cb3f7-ecdc-44cb-ab10-dc95987b7151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='22207_ec4933e0-1ea5-4110-a00b-3b7aee327760']</value>
      <webElementGuid>9762b423-587d-49a2-b0a7-dc7a1f7a68ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[2]/div/div/div/form/section/div/div[11]/div/div/section/div/div/div/div[3]/select</value>
      <webElementGuid>59de9af0-b9a7-4b2f-a6c2-3614b34cdfa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship to child'])[2]/following::select[1]</value>
      <webElementGuid>6f6c11b7-4bfa-4e66-931b-9aadff46f7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why?'])[1]/following::select[1]</value>
      <webElementGuid>3961b287-310c-4759-a026-7c5c39026329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How are you currently feeding your little one?'])[1]/preceding::select[1]</value>
      <webElementGuid>c08abe04-29f5-499b-810a-5a7964579fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(optional)'])[1]/preceding::select[1]</value>
      <webElementGuid>79bd2ee6-9eba-460f-ad27-8ae6cdc81658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>e4b27587-306e-4a7f-b62f-f4cc67a17716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '22207_ec4933e0-1ea5-4110-a00b-3b7aee327760' and @name = '22207_ec4933e0-1ea5-4110-a00b-3b7aee327760' and @placeholder = 'Select one' and (text() = 'Select oneMotherFatherGrandparentOthers' or . = 'Select oneMotherFatherGrandparentOthers')]</value>
      <webElementGuid>4652ec3b-f123-45ea-9182-7983ce195d03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
