<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Relationship_Dad</name>
   <tag></tag>
   <elementGuidId>db51ab21-e399-4b5c-9c8b-864e57c8d274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@aria-labelledby='child1registerChildListCaregiverTypeCodeField__label']/div/div/div/label/div[text()='Dad']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
