<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>u_We do not sell consumer information to th_51c14f</name>
   <tag></tag>
   <elementGuidId>3d49f324-e4b9-4fa2-b234-9c8266e547a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>u</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='dsar-webform-welcome-text']/span/p/strong/u</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>u</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We do not sell consumer information to third parties. </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dsar-webform-welcome-text&quot;)/span[1]/p[1]/strong[1]/u[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='dsar-webform-welcome-text']/span/p/strong/u</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Required)'])[1]/preceding::u[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//u</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = 'We do not sell consumer information to third parties. ' or . = 'We do not sell consumer information to third parties. ')]</value>
   </webElementXpaths>
</WebElementEntity>
