<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_482f5eb3-b873-4b90-ad22-00b8_0f9439</name>
   <tag></tag>
   <elementGuidId>1fce3591-0f5a-4015-8790-2bc5fd20b8a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#482f5eb3-b873-4b90-ad22-00b813ddb188_882</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='482f5eb3-b873-4b90-ad22-00b813ddb188_882']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder = 'Zip Code*']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__input form-control__input--address-postal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>482f5eb3-b873-4b90-ad22-00b813ddb188_882</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>482f5eb3-b873-4b90-ad22-00b813ddb188</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip Code*</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;482f5eb3-b873-4b90-ad22-00b813ddb188_882&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='482f5eb3-b873-4b90-ad22-00b813ddb188_882']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/article/section[2]/div/div[3]/div/div/div/form/section/div/div[2]/div/div/section/div/div[2]/div[3]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '482f5eb3-b873-4b90-ad22-00b813ddb188_882' and @name = '482f5eb3-b873-4b90-ad22-00b813ddb188' and @placeholder = 'Zip Code*' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
